#!/usr/bin/env python3
"""Generate the LuLang Telegram Bot API surface from structured documentation."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def snake(name: str) -> str:
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name).lower()
    value = re.sub(r"[^a-z0-9_]", "_", value)
    return value


def comment(value: str, prefix: str = "// ") -> str:
    return "\n".join(prefix + line.strip() for line in value.splitlines() if line.strip())


def primitive(value: str) -> str | None:
    return {
        "Integer": "i64",
        "Int": "i64",
        "String": "str",
        "Boolean": "bool",
        "True": "bool",
        "Float": "f64",
        "Float number": "f64",
    }.get(value)


def named_type(value: str, known: set[str]) -> str | None:
    if value in known:
        return value
    return None


def value_type(value: str, known: set[str]) -> str:
    scalar = primitive(value)
    if scalar:
        return scalar
    named = named_type(value, known)
    if named:
        return named
    return "str"


def decode_expr(source: str, field: str, value: str, known: set[str]) -> str:
    raw = f'json_get({source}, "{field}")'
    scalar = primitive(value)
    if scalar == "i64":
        return f"json_i64({raw})"
    if scalar == "f64":
        return f"json_f64({raw})"
    if scalar == "bool":
        return f"json_bool({raw})"
    if scalar == "str":
        return f"json_string({raw})"
    named = named_type(value, known)
    if named:
        return f"{named} {{ json: {raw} }}"
    return raw


def encode_expr(source: str, value: str, known: set[str]) -> str:
    scalar = primitive(value)
    if scalar == "i64":
        return f"json_from_i64({source})"
    if scalar == "bool":
        return f"json_from_bool({source})"
    if scalar == "str":
        return f"json_quote({source})"
    if scalar == "f64":
        return f"json_from_f64({source})"
    if value in known:
        return f"{source}.json"
    return source


def generate(document: dict[str, object]) -> str:
    types = list(document["types"])
    unions = list(document["union_types"])
    methods = list(document["methods"])
    known = {item["name"] for item in types + unions}
    out: list[str] = [
        "// Code generated by tools/telegram_codegen.py; DO NOT EDIT.",
        f"// Source: {document.get('source', 'structured Telegram Bot API documentation')}",
        f"// Telegram Bot API {document.get('version', 'unknown')} ({document.get('released', 'unknown')})",
        "",
        "type TelegramError {",
        "  error_code: i64,",
        "  description: str,",
        "}",
        "",
    ]

    for item in unions:
        out.extend(
            [
                comment(item["description"]),
                f"// Variants: {', '.join(item['types'])}",
                f"type {item['name']} {{",
                "  json: str,",
                "}",
                "",
            ]
        )
    for item in types:
        out.extend(
            [
                comment(item["description"]),
                f"type {item['name']} {{",
                "  json: str,",
                "}",
                "",
            ]
        )

    for item in types:
        prefix = snake(item["name"])
        for field in item["fields"]:
            field_name = snake(field["name"])
            ty = value_type(field["type"], known)
            out.append(comment(field["description"]))
            out.append(f"fn {prefix}_has_{field_name}(value: {item['name']}): bool {{")
            out.append(f'  return json_has(value.json, "{field["name"]}")')
            out.append("}")
            out.append(f"fn {prefix}_get_{field_name}(value: {item['name']}): {ty} {{")
            out.append(f'  return {decode_expr("value.json", field["name"], field["type"], known)}')
            out.append("}")
            out.append("")

    for method in methods:
        method_snake = snake(method["name"])
        params_name = method["name"][0].upper() + method["name"][1:] + "Params"
        response_name = method["name"][0].upper() + method["name"][1:] + "Response"
        required = [parameter for parameter in method["parameters"] if parameter["required"]]
        result_ty = value_type(method["result_type"], known)
        out.extend([comment(method["description"]), f"type {params_name} {{"])
        for parameter in required:
            out.append(comment(parameter["description"], "  // "))
            out.append(f"  {snake(parameter['name'])}: {value_type(parameter['type'], known)},")
        out.extend(
            [
                "  // JSON object containing any optional parameters.",
                "  optional: str,",
                "}",
                "",
                f"type {response_name} {{",
                "  ok: bool,",
                "  error: TelegramError,",
                f"  result: {result_ty},",
                "  raw: str,",
                "}",
                "",
                f"fn {method_snake}_params_json(params: {params_name}): str {{",
                '  var body = "{"',
                "  var first = true",
            ]
        )
        for parameter in required:
            name = snake(parameter["name"])
            encoded = encode_expr(f"params.{name}", parameter["type"], known)
            out.extend(
                [
                    "  if not first { body = concat(body, \",\") }",
                    f'  body = concat(body, "\\"{parameter["name"]}\\":")',
                    f"  body = concat(body, {encoded})",
                    "  first = false",
                ]
            )
        out.extend(
            [
                "  if len(params.optional) > 2 {",
                "    if not first { body = concat(body, \",\") }",
                "    body = concat(body, substr(params.optional, 1, len(params.optional) - 1))",
                "  }",
                '  return concat(body, "}")',
                "}",
                "",
                f"fn {method_snake}(token: str, params: {params_name}): {response_name} {{",
                f'  let envelope = json_request("{method["name"]}", {method_snake}_params_json(params))',
                "  let raw = lutelegram_request(token, envelope)",
                '  let ok = json_bool(json_get(raw, "ok"))',
                '  let error = TelegramError { error_code: json_i64(json_get(raw, "error_code")), description: json_string(json_get(raw, "description")) }',
                f'  let result = {decode_expr("raw", "result", method["result_type"], known)}',
                f"  return {response_name} {{ ok: ok, error: error, result: result, raw: raw }}",
                "}",
                "",
            ]
        )

    return "\n".join(out).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("document", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--runtime", type=Path, help="prepend the handwritten LuLang runtime")
    args = parser.parse_args()
    document = json.loads(args.document.read_text(encoding="utf-8"))
    generated = generate(document)
    if args.runtime:
        generated = args.runtime.read_text(encoding="utf-8").rstrip() + "\n\n" + generated
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8")
    print(
        f"generated {len(document['types'])} types, {len(document['union_types'])} unions, "
        f"and {len(document['methods'])} methods in {args.output}"
    )


if __name__ == "__main__":
    main()
