use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::Path;

#[derive(Clone, Debug, PartialEq)]
enum ConstantValue {
    I64(i64),
    F64(f64),
}

#[derive(Clone, Debug)]
struct Constant {
    name: String,
    value: ConstantValue,
}

#[derive(Clone, Debug)]
struct CEnum {
    name: String,
    variants: Vec<(String, i64)>,
}

#[derive(Clone, Debug, Default)]
struct CType {
    base: String,
    pointers: usize,
    is_const: bool,
    function_pointer: bool,
}

#[derive(Clone, Debug)]
struct CParam {
    name: String,
    ty: CType,
}

#[derive(Clone, Debug)]
struct CFunction {
    name: String,
    params: Vec<CParam>,
    ret: CType,
    variadic: bool,
}

#[derive(Debug, Default)]
struct Header {
    constants: Vec<Constant>,
    enums: Vec<CEnum>,
    functions: Vec<CFunction>,
    aliases: BTreeMap<String, CType>,
    structs: BTreeSet<String>,
    warnings: Vec<String>,
}

pub struct Generated {
    pub source: String,
    pub warnings: Vec<String>,
    pub imported_functions: usize,
}

pub fn generate(header: &str, input: &Path, library: &str) -> Result<Generated, String> {
    let mut parsed = parse_header(header)?;
    let mut source = String::new();
    let _ = writeln!(
        source,
        "// Generated by `lu bindgen` from {}.",
        input.display()
    );
    source.push_str(
        "// Only declarations with an exact lulang boundary representation are emitted.\n",
    );
    let _ = writeln!(source, "// C library: {}\n", library);

    for structure in &parsed.structs {
        let _ = writeln!(
            source,
            "// Opaque C aggregate; usable only behind c_ptr[{}].",
            structure
        );
        let _ = writeln!(source, "type {} {{}}\n", structure);
    }

    for declaration in &parsed.enums {
        if declaration
            .variants
            .iter()
            .enumerate()
            .all(|(index, (_, value))| *value == index as i64)
        {
            let _ = writeln!(source, "enum {} {{", declaration.name);
            for (name, _) in &declaration.variants {
                let _ = writeln!(source, "  {},", name);
            }
            source.push_str("}\n\n");
        } else {
            parsed.warnings.push(format!(
                "enum `{}` has non-sequential C values and was not emitted",
                declaration.name
            ));
        }
    }

    for constant in &parsed.constants {
        if is_lulang_builtin(&constant.name) {
            parsed.warnings.push(format!(
                "macro `{}` collides with a lulang builtin and was not emitted",
                constant.name
            ));
            continue;
        }
        match constant.value {
            ConstantValue::I64(value) => {
                let _ = writeln!(
                    source,
                    "fn {}(): i64 {{\n  return {}\n}}\n",
                    constant.name, value
                );
            }
            ConstantValue::F64(value) => {
                let mut rendered = format!("{value:.17}");
                while rendered.ends_with('0') && rendered.contains('.') {
                    rendered.pop();
                }
                if rendered.ends_with('.') {
                    rendered.push('0');
                }
                let _ = writeln!(
                    source,
                    "fn {}(): f64 {{\n  return {}\n}}\n",
                    constant.name, rendered
                );
            }
        }
    }

    let mut imported = 0;
    for function in &parsed.functions {
        match render_function(function, &parsed.aliases, library) {
            Ok(declaration) => {
                source.push_str(&declaration);
                source.push('\n');
                imported += 1;
            }
            Err(reason) => parsed.warnings.push(format!(
                "function `{}` was skipped: {}",
                function.name, reason
            )),
        }
    }
    if imported == 0 {
        parsed
            .warnings
            .push("no directly ABI-safe C functions were found".into());
    }

    if !parsed.warnings.is_empty() {
        source.push_str("// Bindgen diagnostics:\n");
        for warning in &parsed.warnings {
            let _ = writeln!(source, "// - {}", warning);
        }
    }
    Ok(Generated {
        source,
        warnings: parsed.warnings,
        imported_functions: imported,
    })
}

fn render_function(
    function: &CFunction,
    aliases: &BTreeMap<String, CType>,
    library: &str,
) -> Result<String, String> {
    if function.variadic {
        return Err("variadic functions are not supported".into());
    }
    if function.name.starts_with("lu_") {
        return Err("the `lu_` symbol prefix is reserved by the runtime".into());
    }
    if is_lulang_builtin(&function.name) {
        return Err("name collides with a lulang builtin".into());
    }
    let ret = map_type(&function.ret, aliases, true)?;
    let mut params = Vec::new();
    let mut int_classes = 0usize;
    let mut float_classes = 0usize;
    for (index, parameter) in function.params.iter().enumerate() {
        let ty = map_type(&parameter.ty, aliases, false)?;
        match ty.as_str() {
            "f64" => float_classes += 1,
            "str" => int_classes += 2,
            _ => int_classes += 1,
        }
        params.push(format!(
            "{}: {}",
            sanitize_identifier(&parameter.name, index),
            ty
        ));
    }
    if int_classes > 6 || float_classes > 8 {
        return Err(format!(
            "signature needs {int_classes} integer-class and {float_classes} float-class registers; maximum is 6 and 8"
        ));
    }
    let declaration = format!(
        "extern \"{}\" fn {}({})",
        escape_string(library),
        function.name,
        params.join(", ")
    );
    Ok(if ret == "()" {
        format!("{declaration}\n")
    } else {
        format!("{declaration}: {ret}\n")
    })
}

fn map_type(
    ty: &CType,
    aliases: &BTreeMap<String, CType>,
    return_position: bool,
) -> Result<String, String> {
    let resolved = resolve_alias(ty, aliases)?;
    if resolved.function_pointer {
        return Err("function pointers are deferred with callbacks".into());
    }
    if resolved.pointers != 0 {
        let mut pointee = match canonical_base(&resolved.base).as_str() {
            "double" => "f64".into(),
            "int64_t" | "signed long" | "signed long int" | "long" | "long int" | "intptr_t"
            | "ptrdiff_t" => "i64".into(),
            base if base.starts_with("struct ") || base.starts_with("union ") => base
                .split_whitespace()
                .nth(1)
                .filter(|name| valid_identifier(name))
                .unwrap_or("()")
                .into(),
            _ => "()".into(),
        };
        for _ in 0..resolved.pointers {
            pointee = format!("c_ptr[{pointee}]");
        }
        return Ok(pointee);
    }
    match canonical_base(&resolved.base).as_str() {
        "void" if return_position => Ok("()".into()),
        "void" => Err("a parameter cannot have type void".into()),
        "double" => Ok("f64".into()),
        "int64_t" | "signed long" | "signed long int" | "long" | "long int" | "intptr_t"
        | "ptrdiff_t" => Ok("i64".into()),
        "bool" | "_Bool" => Err(
            "C bool is not the lulang boundary bool (`int64_t`); a conversion shim is required"
                .into(),
        ),
        "float" => Err("C float requires direct f32 boundary support".into()),
        base if base.starts_with("enum ") => Err(
            "C enums use implementation-defined integer width; a conversion shim is required"
                .into(),
        ),
        base if base.starts_with("struct ") || base.starts_with("union ") => {
            Err("by-value aggregate parameters require `@c_layout` boundary records".into())
        }
        base => Err(format!(
            "C type `{base}` has no exact boundary representation"
        )),
    }
}

fn resolve_alias(ty: &CType, aliases: &BTreeMap<String, CType>) -> Result<CType, String> {
    let mut current = ty.clone();
    let mut seen = BTreeSet::new();
    while let Some(alias) = aliases.get(&current.base) {
        if !seen.insert(current.base.clone()) {
            return Err(format!("cyclic typedef involving `{}`", current.base));
        }
        let mut next = alias.clone();
        next.pointers += current.pointers;
        next.is_const |= current.is_const;
        next.function_pointer |= current.function_pointer;
        current = next;
    }
    Ok(current)
}

fn canonical_base(base: &str) -> String {
    base.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn sanitize_identifier(name: &str, index: usize) -> String {
    let fallback = format!("arg{index}");
    let name = if name.is_empty() { &fallback } else { name };
    match name {
        "fn" | "type" | "enum" | "extern" | "export" | "inout" | "main" | "property"
        | "operator" | "let" | "var" | "return" | "if" | "else" | "for" | "while" | "sum"
        | "true" | "false" => format!("c_{name}"),
        _ => name.into(),
    }
}

fn is_lulang_builtin(name: &str) -> bool {
    matches!(
        name,
        "print"
            | "puti"
            | "putf"
            | "putb"
            | "puts"
            | "putsp"
            | "putnl"
            | "nargs"
            | "arg"
            | "chr"
            | "concat"
            | "read_file"
            | "write_file"
            | "sqrt"
            | "sin"
            | "cos"
            | "acos"
            | "abs"
            | "floor"
            | "min"
            | "max"
            | "pow"
            | "atan2"
            | "float"
            | "f32"
            | "int"
            | "len"
            | "substr"
            | "arr"
    )
}

fn escape_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn parse_header(source: &str) -> Result<Header, String> {
    let source = source.replace("\\\n", " ");
    let (without_directives, constants, mut warnings) = parse_directives(&source);
    let cleaned = strip_comments(&without_directives)?;
    let tokens = tokenize(&cleaned)?;
    let declarations = split_declarations(&tokens);
    let mut header = Header {
        constants,
        warnings: std::mem::take(&mut warnings),
        ..Header::default()
    };
    for declaration in declarations {
        if declaration.is_empty() {
            continue;
        }
        if declaration.first().is_some_and(|token| token == "typedef") {
            parse_typedef(&declaration, &mut header);
        } else if declaration.first().is_some_and(|token| token == "enum") {
            if let Some(enumeration) = parse_enum(&declaration, None) {
                header.enums.push(enumeration);
            }
        } else if declaration
            .first()
            .is_some_and(|token| token == "struct" || token == "union")
        {
            index_struct(&declaration, &mut header);
        } else if let Some(function) = parse_function(&declaration) {
            header.functions.push(function);
        }
    }
    Ok(header)
}

fn parse_directives(source: &str) -> (String, Vec<Constant>, Vec<String>) {
    let mut output = String::new();
    let mut constants = Vec::new();
    let mut warnings = Vec::new();
    for line in source.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("#define") {
            let mut parts = rest.split_whitespace();
            let Some(name) = parts.next() else {
                continue;
            };
            if name.contains('(') {
                continue;
            }
            let value = parts.collect::<Vec<_>>().join("");
            if value.is_empty() {
                continue;
            }
            match parse_constant(&value) {
                Some(parsed) if valid_identifier(name) => constants.push(Constant {
                    name: name.into(),
                    value: parsed,
                }),
                Some(_) => warnings.push(format!("macro `{name}` is not a valid lulang name")),
                None => {}
            }
        } else if !trimmed.starts_with('#') {
            output.push_str(line);
            output.push('\n');
        }
    }
    (output, constants, warnings)
}

fn parse_constant(value: &str) -> Option<ConstantValue> {
    let mut value = value.trim();
    while value.starts_with('(') && value.ends_with(')') && value.len() > 2 {
        value = &value[1..value.len() - 1];
    }
    let value = value.trim_end_matches(|ch: char| matches!(ch, 'u' | 'U' | 'l' | 'L' | 'f' | 'F'));
    if value.contains(['.', 'e', 'E']) {
        return value.parse::<f64>().ok().map(ConstantValue::F64);
    }
    let (negative, digits) = value
        .strip_prefix('-')
        .map_or((false, value), |rest| (true, rest));
    let parsed = if let Some(hex) = digits
        .strip_prefix("0x")
        .or_else(|| digits.strip_prefix("0X"))
    {
        i64::from_str_radix(hex, 16).ok()
    } else if digits.starts_with('0') && digits.len() > 1 {
        i64::from_str_radix(&digits[1..], 8).ok()
    } else {
        digits.parse::<i64>().ok()
    }?;
    Some(ConstantValue::I64(if negative { -parsed } else { parsed }))
}

fn strip_comments(source: &str) -> Result<String, String> {
    let chars: Vec<char> = source.chars().collect();
    let mut output = String::with_capacity(chars.len());
    let mut index = 0;
    while index < chars.len() {
        if chars[index] == '/' && chars.get(index + 1) == Some(&'/') {
            index += 2;
            while index < chars.len() && chars[index] != '\n' {
                index += 1;
            }
        } else if chars[index] == '/' && chars.get(index + 1) == Some(&'*') {
            index += 2;
            while index + 1 < chars.len() && !(chars[index] == '*' && chars[index + 1] == '/') {
                if chars[index] == '\n' {
                    output.push('\n');
                }
                index += 1;
            }
            if index + 1 >= chars.len() {
                return Err("unterminated block comment in C header".into());
            }
            index += 2;
        } else {
            output.push(chars[index]);
            index += 1;
        }
    }
    Ok(output)
}

fn tokenize(source: &str) -> Result<Vec<String>, String> {
    let chars: Vec<char> = source.chars().collect();
    let mut tokens = Vec::new();
    let mut index = 0;
    while index < chars.len() {
        if chars[index].is_whitespace() {
            index += 1;
        } else if chars[index].is_ascii_alphabetic() || chars[index] == '_' {
            let start = index;
            index += 1;
            while index < chars.len()
                && (chars[index].is_ascii_alphanumeric() || chars[index] == '_')
            {
                index += 1;
            }
            tokens.push(chars[start..index].iter().collect());
        } else if chars[index].is_ascii_digit()
            || (chars[index] == '-'
                && chars
                    .get(index + 1)
                    .is_some_and(|next| next.is_ascii_digit()))
        {
            let start = index;
            index += 1;
            while index < chars.len()
                && (chars[index].is_ascii_alphanumeric() || matches!(chars[index], '.' | '+' | '-'))
            {
                index += 1;
            }
            tokens.push(chars[start..index].iter().collect());
        } else if chars[index] == '"' || chars[index] == '\'' {
            let quote = chars[index];
            let start = index;
            index += 1;
            let mut escaped = false;
            while index < chars.len() {
                let ch = chars[index];
                index += 1;
                if escaped {
                    escaped = false;
                } else if ch == '\\' {
                    escaped = true;
                } else if ch == quote {
                    break;
                }
            }
            if chars.get(index.saturating_sub(1)) != Some(&quote) {
                return Err("unterminated C string or character literal".into());
            }
            tokens.push(chars[start..index].iter().collect());
        } else if chars[index] == '.'
            && chars.get(index + 1) == Some(&'.')
            && chars.get(index + 2) == Some(&'.')
        {
            tokens.push("...".into());
            index += 3;
        } else {
            tokens.push(chars[index].to_string());
            index += 1;
        }
    }
    Ok(tokens)
}

fn split_declarations(tokens: &[String]) -> Vec<Vec<String>> {
    let mut declarations = Vec::new();
    let mut current = Vec::new();
    let mut brace_depth = 0usize;
    for token in tokens {
        match token.as_str() {
            "{" => brace_depth += 1,
            "}" => brace_depth = brace_depth.saturating_sub(1),
            ";" if brace_depth == 0 => {
                declarations.push(std::mem::take(&mut current));
                continue;
            }
            _ => {}
        }
        current.push(token.clone());
    }
    if !current.is_empty() {
        declarations.push(current);
    }
    declarations
}

fn parse_typedef(tokens: &[String], header: &mut Header) {
    let body = &tokens[1..];
    if body.first().is_some_and(|token| token == "enum") {
        let alias = body.last().filter(|token| valid_identifier(token)).cloned();
        if let Some(enumeration) = parse_enum(body, alias.clone()) {
            if let Some(alias) = alias {
                header.aliases.insert(
                    alias.clone(),
                    CType {
                        base: format!("enum {alias}"),
                        ..CType::default()
                    },
                );
            }
            header.enums.push(enumeration);
        }
        return;
    }
    if body
        .first()
        .is_some_and(|token| token == "struct" || token == "union")
    {
        index_struct(body, header);
        if let Some(alias) = body.last().filter(|token| valid_identifier(token)) {
            let tag = body.get(1).filter(|token| valid_identifier(token));
            let base_name = tag.unwrap_or(alias);
            header.aliases.insert(
                alias.clone(),
                CType {
                    base: format!("{} {}", body[0], base_name),
                    ..CType::default()
                },
            );
        }
        return;
    }
    if let Some((name, ty)) = parse_alias(body) {
        header.aliases.insert(name, ty);
    }
}

fn parse_alias(tokens: &[String]) -> Option<(String, CType)> {
    if tokens.iter().any(|token| token == "(") {
        return None;
    }
    let name_index = tokens.iter().rposition(|token| valid_identifier(token))?;
    let name = tokens[name_index].clone();
    let ty = parse_type_tokens(&tokens[..name_index]);
    (!ty.base.is_empty()).then_some((name, ty))
}

fn parse_enum(tokens: &[String], alias: Option<String>) -> Option<CEnum> {
    let open = tokens.iter().position(|token| token == "{")?;
    let close = tokens.iter().rposition(|token| token == "}")?;
    let tag = tokens
        .get(1)
        .filter(|token| valid_identifier(token))
        .cloned();
    let name = alias.or(tag)?;
    let mut variants = Vec::new();
    let mut index = open + 1;
    let mut next_value = 0i64;
    while index < close {
        if tokens[index] == "," {
            index += 1;
            continue;
        }
        if !valid_identifier(&tokens[index]) {
            return None;
        }
        let variant = tokens[index].clone();
        index += 1;
        let value = if tokens.get(index).is_some_and(|token| token == "=") {
            index += 1;
            let parsed = tokens
                .get(index)
                .and_then(|token| parse_constant(token))
                .and_then(|constant| match constant {
                    ConstantValue::I64(value) => Some(value),
                    ConstantValue::F64(_) => None,
                })?;
            index += 1;
            parsed
        } else {
            next_value
        };
        variants.push((variant, value));
        next_value = value.saturating_add(1);
        while index < close && tokens[index] != "," {
            index += 1;
        }
    }
    (!variants.is_empty()).then_some(CEnum { name, variants })
}

fn index_struct(tokens: &[String], header: &mut Header) {
    if let Some(name) = tokens.get(1).filter(|token| valid_identifier(token)) {
        header.structs.insert(name.clone());
    }
    if let Some(close) = tokens.iter().rposition(|token| token == "}") {
        if let Some(alias) = tokens
            .get(close + 1)
            .filter(|token| valid_identifier(token))
        {
            header.structs.insert(alias.clone());
        }
    }
}

fn parse_function(tokens: &[String]) -> Option<CFunction> {
    let open = tokens.iter().position(|token| token == "(")?;
    let close = matching_close(tokens, open)?;
    if close + 1 != tokens.len() || open == 0 {
        return None;
    }
    let name_index = (0..open)
        .rev()
        .find(|index| valid_identifier(&tokens[*index]))?;
    let name = tokens[name_index].clone();
    let ret = parse_type_tokens(&tokens[..name_index]);
    if ret.base.is_empty() {
        return None;
    }
    let mut params = Vec::new();
    let mut variadic = false;
    let slices = split_commas(&tokens[open + 1..close]);
    if !(slices.len() == 1 && slices[0].len() == 1 && slices[0][0] == "void") {
        for (index, parameter) in slices.into_iter().enumerate() {
            if parameter.len() == 1 && parameter[0] == "..." {
                variadic = true;
                continue;
            }
            if parameter.is_empty() {
                continue;
            }
            params.push(parse_parameter(parameter, index));
        }
    }
    Some(CFunction {
        name,
        params,
        ret,
        variadic,
    })
}

fn parse_parameter(tokens: &[String], index: usize) -> CParam {
    if let Some(open) = tokens.iter().position(|token| token == "(") {
        if tokens.get(open + 1).is_some_and(|token| token == "*") {
            let name = tokens
                .get(open + 2)
                .filter(|token| valid_identifier(token))
                .cloned()
                .unwrap_or_else(|| format!("arg{index}"));
            let mut ty = parse_type_tokens(&tokens[..open]);
            ty.function_pointer = true;
            return CParam { name, ty };
        }
    }
    let name_index = tokens
        .iter()
        .rposition(|token| valid_identifier(token) && !is_type_word(token));
    let name = name_index
        .map(|position| tokens[position].clone())
        .unwrap_or_else(|| format!("arg{index}"));
    let type_end = name_index.unwrap_or(tokens.len());
    let mut ty = parse_type_tokens(&tokens[..type_end]);
    if tokens
        .get(type_end + 1..)
        .is_some_and(|tail| tail.iter().any(|token| token == "["))
    {
        ty.pointers += 1;
    }
    CParam { name, ty }
}

fn parse_type_tokens(tokens: &[String]) -> CType {
    let mut ty = CType::default();
    let mut words = Vec::new();
    let mut index = 0;
    while index < tokens.len() {
        match tokens[index].as_str() {
            "*" => ty.pointers += 1,
            "const" | "__const" | "__const__" => ty.is_const = true,
            "volatile" | "restrict" | "__restrict" | "__restrict__" | "extern" | "static"
            | "inline" | "__inline" | "__inline__" => {}
            "__attribute__" | "__declspec" => {
                if tokens.get(index + 1).is_some_and(|token| token == "(") {
                    if let Some(close) = matching_close(tokens, index + 1) {
                        index = close;
                    }
                }
            }
            token => words.push(token.to_string()),
        }
        index += 1;
    }
    ty.base = canonical_base(&words.join(" "));
    ty
}

fn split_commas(tokens: &[String]) -> Vec<&[String]> {
    let mut parts = Vec::new();
    let mut start = 0;
    let mut depth = 0usize;
    for (index, token) in tokens.iter().enumerate() {
        match token.as_str() {
            "(" | "[" | "{" => depth += 1,
            ")" | "]" | "}" => depth = depth.saturating_sub(1),
            "," if depth == 0 => {
                parts.push(&tokens[start..index]);
                start = index + 1;
            }
            _ => {}
        }
    }
    parts.push(&tokens[start..]);
    parts
}

fn matching_close(tokens: &[String], open: usize) -> Option<usize> {
    let pair = match tokens.get(open)?.as_str() {
        "(" => (")", "("),
        "[" => ("]", "["),
        "{" => ("}", "{"),
        _ => return None,
    };
    let mut depth = 0usize;
    for (index, token) in tokens.iter().enumerate().skip(open) {
        if token == pair.1 {
            depth += 1;
        } else if token == pair.0 {
            depth -= 1;
            if depth == 0 {
                return Some(index);
            }
        }
    }
    None
}

fn valid_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    chars
        .next()
        .is_some_and(|first| first.is_ascii_alphabetic() || first == '_')
        && chars.all(|ch| ch.is_ascii_alphanumeric() || ch == '_')
}

fn is_type_word(value: &str) -> bool {
    matches!(
        value,
        "void"
            | "char"
            | "short"
            | "int"
            | "long"
            | "signed"
            | "unsigned"
            | "float"
            | "double"
            | "bool"
            | "_Bool"
            | "const"
            | "volatile"
            | "restrict"
            | "struct"
            | "union"
            | "enum"
            | "int8_t"
            | "int16_t"
            | "int32_t"
            | "int64_t"
            | "uint8_t"
            | "uint16_t"
            | "uint32_t"
            | "uint64_t"
            | "size_t"
            | "ssize_t"
            | "intptr_t"
            | "uintptr_t"
            | "ptrdiff_t"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_safe_functions_constants_and_sequential_enums() {
        let header = r#"
            #define LIMIT 0x10
            #define RATE 0.125
            typedef int64_t index_t;
            typedef enum state { IDLE = 0, BUSY = 1 } state;
            double hypot(double x, double y);
            int64_t count(index_t n);
        "#;
        let generated = generate(header, Path::new("sample.h"), "m").unwrap();
        assert!(generated.source.contains("fn LIMIT(): i64"));
        assert!(generated.source.contains("fn RATE(): f64"));
        assert!(generated.source.contains("enum state"));
        assert!(generated
            .source
            .contains("extern \"m\" fn hypot(x: f64, y: f64): f64"));
        assert!(generated
            .source
            .contains("extern \"m\" fn count(n: i64): i64"));
        assert_eq!(generated.imported_functions, 2);
    }

    #[test]
    fn refuses_types_without_exact_boundary_representations() {
        let header = r#"
            float narrow(float x);
            int ordinary_int(int x);
            void *allocate(size_t size);
            int64_t callback(int64_t (*f)(int64_t));
        "#;
        let generated = generate(header, Path::new("unsafe.h"), "unsafe").unwrap();
        assert_eq!(generated.imported_functions, 0);
        assert!(generated
            .warnings
            .iter()
            .any(|warning| warning.contains("float")));
        assert!(generated
            .warnings
            .iter()
            .any(|warning| warning.contains("size_t")));
        assert!(generated
            .warnings
            .iter()
            .any(|warning| warning.contains("function pointers")));
    }
}
