use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::Path;

#[derive(Clone, Debug, PartialEq)]
enum ConstantValue {
    I64(i64),
    F64(f64),
}

#[derive(Clone, Debug)]
struct Constant {
    name: String,
    value: ConstantValue,
}

#[derive(Clone, Debug)]
struct CEnum {
    name: String,
    variants: Vec<(String, i64)>,
}

#[derive(Clone, Debug, Default)]
struct CType {
    base: String,
    pointers: usize,
    is_const: bool,
    callback: Option<Box<CCallback>>,
}

#[derive(Clone, Debug)]
struct CCallback {
    params: Vec<CParam>,
    ret: CType,
    variadic: bool,
}

#[derive(Clone, Debug)]
struct CParam {
    name: String,
    ty: CType,
    bit_width: Option<String>,
}

#[derive(Clone, Debug)]
struct CFunction {
    name: String,
    params: Vec<CParam>,
    ret: CType,
    variadic: bool,
}

#[derive(Debug, Default)]
struct Header {
    constants: Vec<Constant>,
    enums: Vec<CEnum>,
    functions: Vec<CFunction>,
    aliases: BTreeMap<String, CType>,
    structs: BTreeMap<String, Option<Vec<CParam>>>,
    warnings: Vec<String>,
}

pub struct Generated {
    pub source: String,
    pub shim_source: Option<String>,
    pub warnings: Vec<String>,
    pub imported_functions: usize,
    pub shimmed_functions: usize,
}

pub fn generate(
    header: &str,
    input: &Path,
    library: &str,
    shim_library: Option<&str>,
) -> Result<Generated, String> {
    let mut parsed = parse_header(header)?;
    let mut source = String::new();
    let _ = writeln!(
        source,
        "// Generated by `lu bindgen` from {}.",
        input.display()
    );
    source.push_str(
        "// Only declarations with an exact lulang boundary representation are emitted.\n",
    );
    let _ = writeln!(source, "// C library: {}\n", library);

    for (structure, fields) in &parsed.structs {
        let rendered_fields = fields.as_ref().and_then(|fields| {
            fields
                .iter()
                .enumerate()
                .map(|(index, field)| {
                    if field.bit_width.is_some() {
                        return Err("bitfield requires an adapter".to_string());
                    }
                    map_c_layout_field(&field.ty, &parsed.aliases)
                        .map(|ty| format!("  {}: {},", sanitize_identifier(&field.name, index), ty))
                })
                .collect::<Result<Vec<_>, _>>()
                .ok()
        });
        if let Some(fields) = rendered_fields {
            let _ = writeln!(source, "@c_layout type {} {{", structure);
            for field in fields {
                let _ = writeln!(source, "{field}");
            }
            source.push_str("}\n\n");
        } else if let Some(fields) = fields.as_ref().and_then(|fields| {
            fields
                .iter()
                .enumerate()
                .map(|(index, field)| {
                    map_shim_record_field(&field.ty, &parsed.aliases)
                        .map(|ty| format!("  {}: {},", sanitize_identifier(&field.name, index), ty))
                })
                .collect::<Result<Vec<_>, _>>()
                .ok()
        }) {
            let _ = writeln!(
                source,
                "// Logical adapter record; C storage is constructed only inside the shim."
            );
            let _ = writeln!(source, "type {} {{", structure);
            for field in fields {
                let _ = writeln!(source, "{field}");
            }
            source.push_str("}\n\n");
        } else {
            let _ = writeln!(
                source,
                "// Opaque C aggregate; usable only behind c_ptr[{}].",
                structure
            );
            let _ = writeln!(source, "type {} {{}}\n", structure);
            if fields.is_some() {
                parsed.warnings.push(format!(
                    "struct `{structure}` has fields without exact @c_layout representations and remains opaque"
                ));
            }
        }
    }

    for declaration in &parsed.enums {
        if declaration
            .variants
            .iter()
            .enumerate()
            .all(|(index, (_, value))| *value == index as i64)
        {
            let _ = writeln!(source, "enum {} {{", declaration.name);
            for (name, _) in &declaration.variants {
                let _ = writeln!(source, "  {},", name);
            }
            source.push_str("}\n\n");
        } else {
            parsed.warnings.push(format!(
                "enum `{}` has non-sequential C values and was not emitted",
                declaration.name
            ));
        }
    }

    for constant in &parsed.constants {
        if is_lulang_builtin(&constant.name) {
            parsed.warnings.push(format!(
                "macro `{}` collides with a lulang builtin and was not emitted",
                constant.name
            ));
            continue;
        }
        match constant.value {
            ConstantValue::I64(value) => {
                let _ = writeln!(
                    source,
                    "fn {}(): i64 {{\n  return {}\n}}\n",
                    constant.name, value
                );
            }
            ConstantValue::F64(value) => {
                let mut rendered = format!("{value:.17}");
                while rendered.ends_with('0') && rendered.contains('.') {
                    rendered.pop();
                }
                if rendered.ends_with('.') {
                    rendered.push('0');
                }
                let _ = writeln!(
                    source,
                    "fn {}(): f64 {{\n  return {}\n}}\n",
                    constant.name, rendered
                );
            }
        }
    }

    let mut imported = 0;
    let mut shimmed = 0;
    let mut shim_definitions = Vec::new();
    for function in &parsed.functions {
        if function.variadic {
            if let Some(shim_library) = shim_library {
                match render_variadic_functions(function, &parsed, shim_library) {
                    Ok(variants) => {
                        let count = variants.len();
                        for (declaration, definition) in variants {
                            source.push_str(&declaration);
                            source.push('\n');
                            shim_definitions.push(definition);
                        }
                        imported += count;
                        shimmed += count;
                        parsed.warnings.push(format!(
                            "variadic function `{}` was emitted as {count} explicit typed wrappers covering zero to three i64/f64 varargs",
                            function.name
                        ));
                    }
                    Err(reason) => parsed.warnings.push(format!(
                        "function `{}` was skipped: {}",
                        function.name, reason
                    )),
                }
            } else {
                parsed.warnings.push(format!(
                    "function `{}` was skipped: variadic functions require generated adapter shims",
                    function.name
                ));
            }
            continue;
        }
        match render_function(function, &parsed, library) {
            Ok(declaration) => {
                source.push_str(&declaration);
                source.push('\n');
                imported += 1;
            }
            Err(direct_reason) => {
                let shim = shim_library.and_then(|shim_library| {
                    render_shim_function(function, &parsed, shim_library).ok()
                });
                if let Some((declaration, definition)) = shim {
                    source.push_str(&declaration);
                    source.push('\n');
                    shim_definitions.push(definition);
                    imported += 1;
                    shimmed += 1;
                } else {
                    parsed.warnings.push(format!(
                        "function `{}` was skipped: {}",
                        function.name, direct_reason
                    ));
                }
            }
        }
    }
    if imported == 0 {
        parsed
            .warnings
            .push("no directly ABI-safe C functions were found".into());
    }

    if !parsed.warnings.is_empty() {
        source.push_str("// Bindgen diagnostics:\n");
        for warning in &parsed.warnings {
            let _ = writeln!(source, "// - {}", warning);
        }
    }
    Ok(Generated {
        source,
        shim_source: (!shim_definitions.is_empty()).then(|| {
            format!(
                "#include <stdbool.h>\n#include <stdint.h>\n#include <stdlib.h>\n#include \"{}\"\n\n{}\n",
                escape_c_include(input),
                shim_definitions.join("\n\n")
            )
        }),
        warnings: parsed.warnings,
        imported_functions: imported,
        shimmed_functions: shimmed,
    })
}

fn map_shim_record_field(ty: &CType, aliases: &BTreeMap<String, CType>) -> Result<String, String> {
    let resolved = resolve_alias(ty, aliases)?;
    if resolved.callback.is_some() {
        return Err("function pointer field".into());
    }
    if resolved.pointers != 0 {
        return map_type(&resolved, aliases, false);
    }
    let base = canonical_base(&resolved.base);
    match base.as_str() {
        "double" => Ok("f64".into()),
        "float" => Ok("f32".into()),
        "bool" | "_Bool" => Ok("bool".into()),
        base if is_signed_c_integer(base) || is_narrow_unsigned_c_integer(base) => Ok("i64".into()),
        base if base.starts_with("enum ") => Ok("i64".into()),
        base if base.starts_with("struct ") => base
            .split_whitespace()
            .nth(1)
            .filter(|name| valid_identifier(name))
            .map(String::from)
            .ok_or_else(|| "unnamed struct field".into()),
        _ => Err(format!("field type `{base}` has no adapter representation")),
    }
}

fn render_function(function: &CFunction, header: &Header, library: &str) -> Result<String, String> {
    if function.variadic {
        return Err("variadic functions are not supported".into());
    }
    if function.name.starts_with("lu_") {
        return Err("the `lu_` symbol prefix is reserved by the runtime".into());
    }
    if is_lulang_builtin(&function.name) {
        return Err("name collides with a lulang builtin".into());
    }
    let ret = map_type(&function.ret, &header.aliases, true).or_else(|reason| {
        direct_record_param(&function.ret, header)
            .map(|(name, _, _)| name)
            .map_err(|_| reason)
    })?;
    let mut params = Vec::new();
    let mut int_classes = 0usize;
    let mut float_classes = 0usize;
    let mut index = 0;
    while index < function.params.len() {
        let parameter = &function.params[index];
        if let Some(slice) = direct_slice_pair(function, index, &header.aliases) {
            int_classes += 2;
            params.push(format!(
                "{}: {}",
                sanitize_identifier(&parameter.name, index),
                slice
            ));
            index += 2;
            continue;
        }
        let (ty, ints, floats) = match map_type(&parameter.ty, &header.aliases, false) {
            Ok(ty) => {
                let (ints, floats) = match ty.as_str() {
                    "f64" | "f32" => (0, 1),
                    "str" => (2, 0),
                    _ => (1, 0),
                };
                (ty, ints, floats)
            }
            Err(reason) => direct_record_param(&parameter.ty, header).map_err(|_| reason)?,
        };
        int_classes += ints;
        float_classes += floats;
        params.push(format!(
            "{}: {}",
            sanitize_identifier(&parameter.name, index),
            ty
        ));
        index += 1;
    }
    if int_classes > 6 || float_classes > 8 {
        return Err(format!(
            "signature needs {int_classes} integer-class and {float_classes} float-class registers; maximum is 6 and 8"
        ));
    }
    let declaration = format!(
        "extern \"{}\" fn {}({})",
        escape_string(library),
        function.name,
        params.join(", ")
    );
    Ok(if ret == "()" {
        format!("{declaration}\n")
    } else {
        format!("{declaration}: {ret}\n")
    })
}

fn direct_slice_pair(
    function: &CFunction,
    index: usize,
    aliases: &BTreeMap<String, CType>,
) -> Option<String> {
    let pointer = function.params.get(index)?;
    let length = function.params.get(index + 1)?;
    let pointer_ty = resolve_alias(&pointer.ty, aliases).ok()?;
    let length_ty = resolve_alias(&length.ty, aliases).ok()?;
    if pointer_ty.callback.is_some()
        || pointer_ty.pointers != 1
        || length_ty.callback.is_some()
        || length_ty.pointers != 0
    {
        return None;
    }
    let element = match canonical_base(&pointer_ty.base).as_str() {
        "double" => "f64",
        "int64_t" | "signed long" | "signed long int" | "long" | "long int" | "intptr_t"
        | "ptrdiff_t" => "i64",
        _ => return None,
    };
    if !matches!(
        canonical_base(&length_ty.base).as_str(),
        "int64_t"
            | "signed long"
            | "signed long int"
            | "long"
            | "long int"
            | "intptr_t"
            | "ptrdiff_t"
    ) {
        return None;
    }
    let pointer_name = pointer.name.trim_start_matches('_');
    let length_name = length.name.trim_start_matches('_');
    let related = matches!(length_name, "n" | "len" | "length" | "count")
        || ["len", "length", "count", "size"]
            .iter()
            .any(|suffix| length_name == format!("{pointer_name}_{suffix}"));
    if !related {
        return None;
    }
    Some(format!(
        "{}[{element}]",
        if pointer_ty.is_const {
            "c_slice"
        } else {
            "c_mut_slice"
        }
    ))
}

fn direct_record_param(ty: &CType, header: &Header) -> Result<(String, usize, usize), String> {
    let resolved = resolve_alias(ty, &header.aliases)?;
    if resolved.callback.is_some() || resolved.pointers != 0 {
        return Err("not a by-value record".into());
    }
    let base = canonical_base(&resolved.base);
    let name = base
        .strip_prefix("struct ")
        .filter(|name| valid_identifier(name))
        .ok_or("not a named struct")?;
    let fields = header
        .structs
        .get(name)
        .and_then(Option::as_ref)
        .ok_or("record layout is incomplete")?;
    if fields.is_empty() || fields.len() > 2 {
        return Err("direct records need one or two fields".into());
    }
    let mut class = None;
    for field in fields {
        if field.bit_width.is_some() {
            return Err("record contains a bitfield".into());
        }
        let field = resolve_alias(&field.ty, &header.aliases)?;
        if field.callback.is_some() {
            return Err("record contains a callback".into());
        }
        let field_class = if field.pointers != 0 {
            false
        } else {
            match canonical_base(&field.base).as_str() {
                "double" => true,
                "int64_t" | "signed long" | "signed long int" | "long" | "long int"
                | "intptr_t" | "ptrdiff_t" => false,
                _ => return Err("record field is not a portable 64-bit boundary scalar".into()),
            }
        };
        if class.is_some_and(|class| class != field_class) {
            return Err("record mixes integer and floating register classes".into());
        }
        class = Some(field_class);
    }
    Ok(if class == Some(true) {
        (name.into(), 0, fields.len())
    } else {
        (name.into(), fields.len(), 0)
    })
}

#[derive(Clone, Debug)]
struct ShimBoundaryArg {
    name: String,
    lu_ty: String,
    c_ty: &'static str,
    lu_expr: String,
}

#[derive(Clone, Debug)]
struct ShimParamPlan {
    api_ty: String,
    boundary: Vec<ShimBoundaryArg>,
    c_expr: String,
}

#[derive(Clone, Debug)]
enum ShimReturnKind {
    Unit,
    I64,
    F64,
    F32,
    Bool,
    Pointer,
    Record(ShimRecordReturn),
}

#[derive(Clone, Debug)]
struct ShimRecordReturn {
    name: String,
    c_type: String,
    fields: Vec<ShimReturnField>,
}

#[derive(Clone, Copy, Debug)]
enum ShimReturnFieldKind {
    I64,
    F64,
    F32,
    Bool,
    Pointer,
}

#[derive(Clone, Debug)]
struct ShimReturnField {
    c_name: String,
    lu_name: String,
    kind: ShimReturnFieldKind,
}

fn render_variadic_functions(
    function: &CFunction,
    header: &Header,
    shim_library: &str,
) -> Result<Vec<(String, String)>, String> {
    if function.name.starts_with("lu_") || is_lulang_builtin(&function.name) {
        return Err("function name cannot be wrapped".into());
    }
    let return_kind = plan_shim_return(&function.ret, header)?;
    if matches!(return_kind, ShimReturnKind::Record(_)) {
        return Err("variadic aggregate returns are not supported".into());
    }

    let mut fixed_api_params = Vec::new();
    let mut fixed_boundary = Vec::new();
    let mut fixed_c_args = Vec::new();
    for (index, parameter) in function.params.iter().enumerate() {
        let api_name = sanitize_identifier(&parameter.name, index);
        let plan = plan_shim_param(
            &parameter.ty,
            header,
            &api_name,
            &format!("arg{index}"),
            &api_name,
        )?;
        fixed_api_params.push(format!("{api_name}: {}", plan.api_ty));
        fixed_boundary.extend(plan.boundary);
        fixed_c_args.push(plan.c_expr);
    }

    let mut patterns = vec![Vec::<bool>::new()];
    for arity in 1..=3 {
        for bits in 0..(1usize << arity) {
            patterns.push((0..arity).map(|index| bits & (1 << index) != 0).collect());
        }
    }
    let escaped_library = escape_string(shim_library);
    let mut rendered = Vec::new();
    for pattern in patterns {
        let suffix = if pattern.is_empty() {
            "v0".to_string()
        } else {
            format!(
                "v_{}",
                pattern
                    .iter()
                    .map(|is_float| if *is_float { "f64" } else { "i64" })
                    .collect::<Vec<_>>()
                    .join("_")
            )
        };
        let public_name = format!("{}_{}", function.name, suffix);
        let symbol = format!("__lulang_bindgen_{public_name}");
        let mut api_params = fixed_api_params.clone();
        let mut boundary = fixed_boundary.clone();
        let mut c_args = fixed_c_args.clone();
        for (index, is_float) in pattern.iter().enumerate() {
            let name = format!("vararg{index}");
            let ty = if *is_float { "f64" } else { "i64" };
            api_params.push(format!("{name}: {ty}"));
            boundary.push(ShimBoundaryArg {
                name: name.clone(),
                lu_ty: ty.into(),
                c_ty: if *is_float { "double" } else { "int64_t" },
                lu_expr: name.clone(),
            });
            c_args.push(name);
        }
        let int_classes = boundary
            .iter()
            .filter(|argument| argument.lu_ty != "f64")
            .count();
        let float_classes = boundary
            .iter()
            .filter(|argument| argument.lu_ty == "f64")
            .count();
        if int_classes > 6 || float_classes > 8 {
            continue;
        }

        let boundary_params = boundary
            .iter()
            .map(|argument| format!("{}: {}", argument.name, argument.lu_ty))
            .collect::<Vec<_>>()
            .join(", ");
        let boundary_args = boundary
            .iter()
            .map(|argument| argument.lu_expr.as_str())
            .collect::<Vec<_>>()
            .join(", ");
        let boundary_ret = match &return_kind {
            ShimReturnKind::Unit => "()".into(),
            ShimReturnKind::I64 | ShimReturnKind::Bool => "i64".into(),
            ShimReturnKind::F64 | ShimReturnKind::F32 => "f64".into(),
            ShimReturnKind::Pointer => map_type(&function.ret, &header.aliases, true)?,
            ShimReturnKind::Record(_) => unreachable!(),
        };
        let api_ret = shim_api_return(&return_kind, &function.ret, &header.aliases)?;
        let mut lu = format!("extern \"{escaped_library}\" fn {symbol}({boundary_params})");
        if boundary_ret != "()" {
            let _ = write!(lu, ": {boundary_ret}");
        }
        let _ = write!(lu, "\nfn {public_name}({})", api_params.join(", "));
        if api_ret != "()" {
            let _ = write!(lu, ": {api_ret}");
        }
        lu.push_str(" {\n");
        let call = format!("{symbol}({boundary_args})");
        match &return_kind {
            ShimReturnKind::Unit => {
                let _ = writeln!(lu, "  {call}");
            }
            ShimReturnKind::Bool => {
                let _ = writeln!(lu, "  return {call} != 0");
            }
            ShimReturnKind::F32 => {
                let _ = writeln!(lu, "  return f32({call})");
            }
            _ => {
                let _ = writeln!(lu, "  return {call}");
            }
        }
        lu.push_str("}\n");

        let c_params = boundary
            .iter()
            .map(|argument| format!("{} {}", argument.c_ty, argument.name))
            .collect::<Vec<_>>()
            .join(", ");
        let original_call = format!("{}({})", function.name, c_args.join(", "));
        let (c_ret, c_body) = match &return_kind {
            ShimReturnKind::Unit => ("void", format!("  {original_call};")),
            ShimReturnKind::I64 => ("int64_t", format!("  return (int64_t){original_call};")),
            ShimReturnKind::F64 | ShimReturnKind::F32 => {
                ("double", format!("  return (double){original_call};"))
            }
            ShimReturnKind::Bool => (
                "int64_t",
                format!("  return {original_call} ? INT64_C(1) : INT64_C(0);"),
            ),
            ShimReturnKind::Pointer => ("void *", format!("  return (void *){original_call};")),
            ShimReturnKind::Record(_) => unreachable!(),
        };
        let c = format!(
            "{c_ret} {symbol}({}) {{\n{c_body}\n}}",
            if c_params.is_empty() {
                "void"
            } else {
                &c_params
            }
        );
        rendered.push((lu, c));
    }
    if rendered.is_empty() {
        Err("no typed variadic wrapper fits the boundary register limits".into())
    } else {
        Ok(rendered)
    }
}

fn render_shim_function(
    function: &CFunction,
    header: &Header,
    shim_library: &str,
) -> Result<(String, String), String> {
    if function.variadic {
        return Err("variadic functions cannot use adapter shims".into());
    }
    if function.name.starts_with("lu_") || is_lulang_builtin(&function.name) {
        return Err("function name cannot be wrapped".into());
    }

    let mut api_params = Vec::new();
    let mut boundary = Vec::new();
    let mut c_call_args = Vec::new();
    for (index, parameter) in function.params.iter().enumerate() {
        let api_name = sanitize_identifier(&parameter.name, index);
        let plan = plan_shim_param(
            &parameter.ty,
            header,
            &api_name,
            &format!("arg{index}"),
            &api_name,
        )?;
        api_params.push(format!("{api_name}: {}", plan.api_ty));
        boundary.extend(plan.boundary);
        c_call_args.push(plan.c_expr);
    }
    let return_kind = plan_shim_return(&function.ret, header)?;

    let int_classes = boundary
        .iter()
        .filter(|argument| argument.lu_ty != "f64")
        .count();
    let float_classes = boundary
        .iter()
        .filter(|argument| argument.lu_ty == "f64")
        .count();
    if int_classes > 6 || float_classes > 8 {
        return Err(format!(
            "adapter signature needs {int_classes} integer-class and {float_classes} float-class registers"
        ));
    }

    let symbol = format!("__lulang_bindgen_{}", function.name);
    if let ShimReturnKind::Record(record) = &return_kind {
        return render_shim_record_return(
            function,
            record,
            &api_params,
            &boundary,
            &c_call_args,
            shim_library,
            &symbol,
        );
    }
    let boundary_params = boundary
        .iter()
        .map(|argument| format!("{}: {}", argument.name, argument.lu_ty))
        .collect::<Vec<_>>()
        .join(", ");
    let boundary_ret = match &return_kind {
        ShimReturnKind::Unit => "()".into(),
        ShimReturnKind::F64 | ShimReturnKind::F32 => "f64".into(),
        ShimReturnKind::Pointer => map_type(&function.ret, &header.aliases, true)?,
        ShimReturnKind::I64 | ShimReturnKind::Bool => "i64".into(),
        ShimReturnKind::Record(_) => unreachable!(),
    };
    let mut lu = format!(
        "extern \"{}\" fn {}({})",
        escape_string(shim_library),
        symbol,
        boundary_params
    );
    if boundary_ret != "()" {
        let _ = write!(lu, ": {boundary_ret}");
    }
    lu.push('\n');
    let _ = write!(lu, "fn {}({})", function.name, api_params.join(", "));
    let api_ret = shim_api_return(&return_kind, &function.ret, &header.aliases)?;
    if api_ret != "()" {
        let _ = write!(lu, ": {api_ret}");
    }
    lu.push_str(" {\n");
    let call = format!(
        "{}({})",
        symbol,
        boundary
            .iter()
            .map(|argument| argument.lu_expr.as_str())
            .collect::<Vec<_>>()
            .join(", ")
    );
    match &return_kind {
        ShimReturnKind::Unit => {
            let _ = writeln!(lu, "  {call}");
        }
        ShimReturnKind::Bool => {
            let _ = writeln!(lu, "  return {call} != 0");
        }
        _ => {
            let _ = writeln!(lu, "  return {call}");
        }
    }
    lu.push_str("}\n");

    let c_params = boundary
        .iter()
        .map(|argument| format!("{} {}", argument.c_ty, argument.name))
        .collect::<Vec<_>>()
        .join(", ");
    let original_call = format!("{}({})", function.name, c_call_args.join(", "));
    let (c_ret, c_body) = match &return_kind {
        ShimReturnKind::Unit => ("void", format!("  {original_call};")),
        ShimReturnKind::I64 => ("int64_t", format!("  return (int64_t){original_call};")),
        ShimReturnKind::F64 | ShimReturnKind::F32 => {
            ("double", format!("  return (double){original_call};"))
        }
        ShimReturnKind::Bool => (
            "int64_t",
            format!("  return {original_call} ? INT64_C(1) : INT64_C(0);"),
        ),
        ShimReturnKind::Pointer => ("void *", format!("  return (void *){original_call};")),
        ShimReturnKind::Record(_) => unreachable!(),
    };
    let c = format!(
        "{c_ret} {symbol}({}) {{\n{c_body}\n}}",
        if c_params.is_empty() {
            "void"
        } else {
            &c_params
        }
    );
    Ok((lu, c))
}

fn render_shim_record_return(
    function: &CFunction,
    record: &ShimRecordReturn,
    api_params: &[String],
    boundary: &[ShimBoundaryArg],
    c_call_args: &[String],
    shim_library: &str,
    symbol: &str,
) -> Result<(String, String), String> {
    let boundary_params = boundary
        .iter()
        .map(|argument| format!("{}: {}", argument.name, argument.lu_ty))
        .collect::<Vec<_>>()
        .join(", ");
    let boundary_args = boundary
        .iter()
        .map(|argument| argument.lu_expr.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    let c_params = boundary
        .iter()
        .map(|argument| format!("{} {}", argument.c_ty, argument.name))
        .collect::<Vec<_>>()
        .join(", ");
    let c_params = if c_params.is_empty() {
        "void".to_string()
    } else {
        c_params
    };
    let escaped_library = escape_string(shim_library);
    let free_symbol = format!("{symbol}_release");

    let mut lu =
        format!("extern \"{escaped_library}\" fn {symbol}({boundary_params}): c_ptr[()]\n");
    for field in &record.fields {
        let getter = format!("{symbol}_get_{}", field.lu_name);
        let ret = match field.kind {
            ShimReturnFieldKind::I64 | ShimReturnFieldKind::Bool => "i64",
            ShimReturnFieldKind::F64 | ShimReturnFieldKind::F32 => "f64",
            ShimReturnFieldKind::Pointer => "c_ptr[()]",
        };
        let _ = writeln!(
            lu,
            "extern \"{escaped_library}\" fn {getter}(handle: c_ptr[()]): {ret}"
        );
    }
    let _ = writeln!(
        lu,
        "extern \"{escaped_library}\" fn {free_symbol}(handle: c_ptr[()])"
    );
    let _ = writeln!(
        lu,
        "fn {}({}): {} {{",
        function.name,
        api_params.join(", "),
        record.name
    );
    let _ = writeln!(lu, "  let handle = {symbol}({boundary_args})");
    let _ = writeln!(lu, "  let result = {} {{", record.name);
    for field in &record.fields {
        let getter = format!("{symbol}_get_{}", field.lu_name);
        let call = format!("{getter}(handle)");
        let expression = match field.kind {
            ShimReturnFieldKind::F32 => format!("f32({call})"),
            ShimReturnFieldKind::Bool => format!("{call} != 0"),
            _ => call,
        };
        let _ = writeln!(lu, "    {}: {expression},", field.lu_name);
    }
    lu.push_str("  }\n");
    let _ = writeln!(lu, "  {free_symbol}(handle)");
    lu.push_str("  return result\n}\n");

    let record_c_type = &record.c_type;
    let original_call = format!("{}({})", function.name, c_call_args.join(", "));
    let mut c = format!(
        "void *{symbol}({c_params}) {{\n  {record_c_type} *result = ({record_c_type} *)malloc(sizeof(*result));\n  if (result == NULL) abort();\n  *result = {original_call};\n  return result;\n}}\n"
    );
    for field in &record.fields {
        let getter = format!("{symbol}_get_{}", field.lu_name);
        let access = format!("(({record_c_type} *)handle)->{}", field.c_name);
        let (c_ret, expression) = match field.kind {
            ShimReturnFieldKind::I64 => ("int64_t", format!("(int64_t){access}")),
            ShimReturnFieldKind::F64 | ShimReturnFieldKind::F32 => {
                ("double", format!("(double){access}"))
            }
            ShimReturnFieldKind::Bool => ("int64_t", format!("{access} ? INT64_C(1) : INT64_C(0)")),
            ShimReturnFieldKind::Pointer => ("void *", format!("(void *){access}")),
        };
        let _ = writeln!(
            c,
            "{c_ret} {getter}(void *handle) {{\n  return {expression};\n}}"
        );
    }
    let _ = write!(
        c,
        "void {free_symbol}(void *handle) {{\n  free(handle);\n}}"
    );
    Ok((lu, c))
}

fn plan_shim_param(
    ty: &CType,
    header: &Header,
    api_name: &str,
    boundary_name: &str,
    lu_expr: &str,
) -> Result<ShimParamPlan, String> {
    let resolved = resolve_alias(ty, &header.aliases)?;
    if resolved.callback.is_some() {
        return Err("callbacks are not supported by adapter shims".into());
    }
    if resolved.pointers != 0 {
        let api_ty = map_type(&resolved, &header.aliases, false)?;
        return Ok(ShimParamPlan {
            api_ty: api_ty.clone(),
            boundary: vec![ShimBoundaryArg {
                name: boundary_name.into(),
                lu_ty: api_ty,
                c_ty: "void *",
                lu_expr: lu_expr.into(),
            }],
            c_expr: format!("({}){boundary_name}", c_type_spelling(ty)),
        });
    }
    let base = canonical_base(&resolved.base);
    if let Some(structure) = base.strip_prefix("struct ") {
        let fields = header
            .structs
            .get(structure)
            .and_then(Option::as_ref)
            .ok_or_else(|| format!("struct `{structure}` is opaque"))?;
        let mut boundary = Vec::new();
        let mut initializers = Vec::new();
        for (field_index, field) in fields.iter().enumerate() {
            let lu_field = sanitize_identifier(&field.name, field_index);
            let child = plan_shim_param(
                &field.ty,
                header,
                &lu_field,
                &format!("{boundary_name}_{lu_field}"),
                &format!("{lu_expr}.{lu_field}"),
            )?;
            boundary.extend(child.boundary);
            initializers.push(format!(".{} = {}", field.name, child.c_expr));
        }
        return Ok(ShimParamPlan {
            api_ty: structure.into(),
            boundary,
            c_expr: format!(
                "({}){{ {} }}",
                aggregate_c_spelling(ty, &resolved, &header.aliases),
                initializers.join(", ")
            ),
        });
    }
    let (api_ty, boundary_ty, c_ty, c_expr, lu_boundary_expr) =
        shim_scalar_param(&base, ty, boundary_name, lu_expr)?;
    let _ = api_name;
    Ok(ShimParamPlan {
        api_ty,
        boundary: vec![ShimBoundaryArg {
            name: boundary_name.into(),
            lu_ty: boundary_ty,
            c_ty,
            lu_expr: lu_boundary_expr,
        }],
        c_expr,
    })
}

fn shim_scalar_param(
    base: &str,
    original: &CType,
    boundary_name: &str,
    lu_expr: &str,
) -> Result<(String, String, &'static str, String, String), String> {
    let cast = c_type_spelling(original);
    match base {
        "double" => Ok((
            "f64".into(),
            "f64".into(),
            "double",
            boundary_name.into(),
            lu_expr.into(),
        )),
        "float" => Ok((
            "f32".into(),
            "f64".into(),
            "double",
            format!("({cast}){boundary_name}"),
            format!("float({lu_expr})"),
        )),
        "bool" | "_Bool" => Ok((
            "bool".into(),
            "i64".into(),
            "int64_t",
            format!("({cast})({boundary_name} != 0)"),
            format!("int({lu_expr})"),
        )),
        base if is_signed_c_integer(base) || is_narrow_unsigned_c_integer(base) => Ok((
            "i64".into(),
            "i64".into(),
            "int64_t",
            format!("({cast}){boundary_name}"),
            lu_expr.into(),
        )),
        base if base.starts_with("enum ") => Ok((
            "i64".into(),
            "i64".into(),
            "int64_t",
            format!("({cast}){boundary_name}"),
            lu_expr.into(),
        )),
        _ => Err(format!("C scalar `{base}` cannot use an adapter shim")),
    }
}

fn plan_shim_return(ty: &CType, header: &Header) -> Result<ShimReturnKind, String> {
    let resolved = resolve_alias(ty, &header.aliases)?;
    if resolved.callback.is_some() {
        return Err("function pointer returns are not supported".into());
    }
    if resolved.pointers != 0 {
        return Ok(ShimReturnKind::Pointer);
    }
    let base = canonical_base(&resolved.base);
    match base.as_str() {
        "void" => Ok(ShimReturnKind::Unit),
        "double" => Ok(ShimReturnKind::F64),
        "float" => Ok(ShimReturnKind::F32),
        "bool" | "_Bool" => Ok(ShimReturnKind::Bool),
        base if is_signed_c_integer(base) || is_narrow_unsigned_c_integer(base) => {
            Ok(ShimReturnKind::I64)
        }
        base if base.starts_with("enum ") => Ok(ShimReturnKind::I64),
        base if base.starts_with("struct ") => {
            let name = base
                .split_whitespace()
                .nth(1)
                .filter(|name| valid_identifier(name))
                .ok_or("unnamed struct return")?;
            let fields = header
                .structs
                .get(name)
                .and_then(Option::as_ref)
                .ok_or_else(|| format!("struct `{name}` is opaque"))?;
            let fields = fields
                .iter()
                .enumerate()
                .map(|(index, field)| {
                    let field_ty = resolve_alias(&field.ty, &header.aliases)?;
                    if field_ty.callback.is_some() {
                        return Err("callback fields cannot use a result adapter".into());
                    }
                    let kind = if field_ty.pointers != 0 {
                        ShimReturnFieldKind::Pointer
                    } else {
                        match canonical_base(&field_ty.base).as_str() {
                            "double" => ShimReturnFieldKind::F64,
                            "float" => ShimReturnFieldKind::F32,
                            "bool" | "_Bool" => ShimReturnFieldKind::Bool,
                            base if is_signed_c_integer(base)
                                || is_narrow_unsigned_c_integer(base)
                                || base.starts_with("enum ") =>
                            {
                                ShimReturnFieldKind::I64
                            }
                            _ => {
                                return Err(format!(
                                "field `{}` in struct `{name}` cannot use a flat result adapter",
                                field.name
                            ))
                            }
                        }
                    };
                    Ok(ShimReturnField {
                        c_name: field.name.clone(),
                        lu_name: sanitize_identifier(&field.name, index),
                        kind,
                    })
                })
                .collect::<Result<Vec<_>, String>>()?;
            if fields.is_empty() {
                return Err(format!("struct `{name}` has no adaptable fields"));
            }
            Ok(ShimReturnKind::Record(ShimRecordReturn {
                name: name.into(),
                c_type: aggregate_c_spelling(ty, &resolved, &header.aliases),
                fields,
            }))
        }
        _ => Err(format!("C return type `{base}` cannot use an adapter shim")),
    }
}

fn aggregate_c_spelling(
    original: &CType,
    resolved: &CType,
    aliases: &BTreeMap<String, CType>,
) -> String {
    if original.pointers == 0
        && original.callback.is_none()
        && aliases.contains_key(&original.base)
        && valid_identifier(&original.base)
    {
        original.base.clone()
    } else {
        c_type_spelling(resolved)
    }
}

fn shim_api_return(
    kind: &ShimReturnKind,
    ty: &CType,
    aliases: &BTreeMap<String, CType>,
) -> Result<String, String> {
    Ok(match kind {
        ShimReturnKind::Unit => "()".into(),
        ShimReturnKind::I64 => "i64".into(),
        ShimReturnKind::F64 => "f64".into(),
        ShimReturnKind::F32 => "f32".into(),
        ShimReturnKind::Bool => "bool".into(),
        ShimReturnKind::Pointer => map_type(ty, aliases, true)?,
        ShimReturnKind::Record(record) => record.name.clone(),
    })
}

fn is_signed_c_integer(base: &str) -> bool {
    matches!(
        base,
        "char"
            | "signed char"
            | "short"
            | "short int"
            | "signed short"
            | "signed short int"
            | "int"
            | "signed"
            | "signed int"
            | "int8_t"
            | "int16_t"
            | "int32_t"
            | "int64_t"
            | "signed long"
            | "signed long int"
            | "long"
            | "long int"
            | "ssize_t"
            | "intptr_t"
            | "ptrdiff_t"
    )
}

fn is_narrow_unsigned_c_integer(base: &str) -> bool {
    matches!(
        base,
        "unsigned char"
            | "unsigned short"
            | "unsigned short int"
            | "unsigned int"
            | "uint8_t"
            | "uint16_t"
            | "uint32_t"
    )
}

fn c_type_spelling(ty: &CType) -> String {
    let mut rendered = ty.base.clone();
    for _ in 0..ty.pointers {
        rendered.push_str(" *");
    }
    rendered
}

fn escape_c_include(path: &Path) -> String {
    path.to_string_lossy()
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
}

fn map_type(
    ty: &CType,
    aliases: &BTreeMap<String, CType>,
    return_position: bool,
) -> Result<String, String> {
    let resolved = resolve_alias(ty, aliases)?;
    if let Some(callback) = &resolved.callback {
        if resolved.pointers != 0 {
            return Err("pointers to function pointers are not supported".into());
        }
        if callback.variadic {
            return Err("variadic callback signatures are not supported".into());
        }
        let params = callback
            .params
            .iter()
            .map(|parameter| map_type(&parameter.ty, aliases, false))
            .collect::<Result<Vec<_>, _>>()?;
        let ret = map_type(&callback.ret, aliases, true)?;
        return Ok(format!("c_fn[({})->{ret}]", params.join(",")));
    }
    if resolved.pointers != 0 {
        let mut pointee = match canonical_base(&resolved.base).as_str() {
            "double" => "f64".into(),
            "int64_t" | "signed long" | "signed long int" | "long" | "long int" | "intptr_t"
            | "ptrdiff_t" => "i64".into(),
            base if base.starts_with("struct ") || base.starts_with("union ") => base
                .split_whitespace()
                .nth(1)
                .filter(|name| valid_identifier(name))
                .unwrap_or("()")
                .into(),
            _ => "()".into(),
        };
        for _ in 0..resolved.pointers {
            pointee = format!("c_ptr[{pointee}]");
        }
        return Ok(pointee);
    }
    match canonical_base(&resolved.base).as_str() {
        "void" if return_position => Ok("()".into()),
        "void" => Err("a parameter cannot have type void".into()),
        "double" => Ok("f64".into()),
        "int64_t" | "signed long" | "signed long int" | "long" | "long int" | "intptr_t"
        | "ptrdiff_t" => Ok("i64".into()),
        "bool" | "_Bool" => Err(
            "C bool is not the lulang boundary bool (`int64_t`); a conversion shim is required"
                .into(),
        ),
        "float" => Ok("f32".into()),
        base if base.starts_with("enum ") => Err(
            "C enums use implementation-defined integer width; a conversion shim is required"
                .into(),
        ),
        base if base.starts_with("struct ") || base.starts_with("union ") => {
            Err("by-value aggregate parameters require `@c_layout` boundary records".into())
        }
        base => Err(format!(
            "C type `{base}` has no exact boundary representation"
        )),
    }
}

fn map_c_layout_field(ty: &CType, aliases: &BTreeMap<String, CType>) -> Result<String, String> {
    let resolved = resolve_alias(ty, aliases)?;
    if resolved.callback.is_some() {
        return Err("function pointer field".into());
    }
    if resolved.pointers != 0 {
        return map_type(&resolved, aliases, false);
    }
    match canonical_base(&resolved.base).as_str() {
        "double" => Ok("f64".into()),
        "float" => Ok("f32".into()),
        "int64_t" | "signed long" | "signed long int" | "long" | "long int" | "intptr_t"
        | "ptrdiff_t" => Ok("i64".into()),
        base if base.starts_with("struct ") => base
            .split_whitespace()
            .nth(1)
            .filter(|name| valid_identifier(name))
            .map(String::from)
            .ok_or_else(|| "unnamed struct field".into()),
        _ => Err(format!(
            "C field type `{}` has no exact layout representation",
            resolved.base
        )),
    }
}

fn resolve_alias(ty: &CType, aliases: &BTreeMap<String, CType>) -> Result<CType, String> {
    let mut current = ty.clone();
    let mut seen = BTreeSet::new();
    while let Some(alias) = aliases.get(&current.base) {
        if !seen.insert(current.base.clone()) {
            return Err(format!("cyclic typedef involving `{}`", current.base));
        }
        let mut next = alias.clone();
        next.pointers += current.pointers;
        next.is_const |= current.is_const;
        if current.callback.is_some() {
            next.callback = current.callback.clone();
        }
        current = next;
    }
    Ok(current)
}

fn canonical_base(base: &str) -> String {
    base.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn sanitize_identifier(name: &str, index: usize) -> String {
    let fallback = format!("arg{index}");
    let name = if name.is_empty() { &fallback } else { name };
    match name {
        "fn" | "type" | "enum" | "extern" | "export" | "inout" | "main" | "property"
        | "operator" | "let" | "var" | "return" | "if" | "else" | "for" | "while" | "sum"
        | "true" | "false" => format!("c_{name}"),
        _ => name.into(),
    }
}

fn is_lulang_builtin(name: &str) -> bool {
    matches!(
        name,
        "print"
            | "puti"
            | "putf"
            | "putb"
            | "puts"
            | "putsp"
            | "putnl"
            | "nargs"
            | "arg"
            | "chr"
            | "concat"
            | "read_file"
            | "write_file"
            | "sqrt"
            | "sin"
            | "cos"
            | "acos"
            | "abs"
            | "floor"
            | "min"
            | "max"
            | "pow"
            | "atan2"
            | "float"
            | "f32"
            | "int"
            | "len"
            | "substr"
            | "arr"
    )
}

fn escape_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn parse_header(source: &str) -> Result<Header, String> {
    let source = source.replace("\\\n", " ");
    let (without_directives, constants, mut warnings) = parse_directives(&source);
    let cleaned = strip_comments(&without_directives)?;
    let tokens = tokenize(&cleaned)?;
    let declarations = split_declarations(&tokens);
    let mut header = Header {
        constants,
        warnings: std::mem::take(&mut warnings),
        ..Header::default()
    };
    for declaration in declarations {
        if declaration.is_empty() {
            continue;
        }
        if declaration.first().is_some_and(|token| token == "typedef") {
            parse_typedef(&declaration, &mut header);
        } else if declaration.first().is_some_and(|token| token == "enum") {
            if let Some(enumeration) = parse_enum(&declaration, None) {
                header.enums.push(enumeration);
            }
        } else if declaration
            .first()
            .is_some_and(|token| token == "struct" || token == "union")
        {
            index_struct(&declaration, &mut header);
        } else if let Some(function) = parse_function(&declaration) {
            header.functions.push(function);
        }
    }
    Ok(header)
}

fn parse_directives(source: &str) -> (String, Vec<Constant>, Vec<String>) {
    let mut output = String::new();
    let mut constants = Vec::new();
    let mut warnings = Vec::new();
    for line in source.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("#define") {
            let mut parts = rest.split_whitespace();
            let Some(name) = parts.next() else {
                continue;
            };
            if name.contains('(') {
                continue;
            }
            let value = parts.collect::<Vec<_>>().join("");
            if value.is_empty() {
                continue;
            }
            match parse_constant(&value) {
                Some(parsed) if valid_identifier(name) => constants.push(Constant {
                    name: name.into(),
                    value: parsed,
                }),
                Some(_) => warnings.push(format!("macro `{name}` is not a valid lulang name")),
                None => {}
            }
        } else if !trimmed.starts_with('#') {
            output.push_str(line);
            output.push('\n');
        }
    }
    (output, constants, warnings)
}

fn parse_constant(value: &str) -> Option<ConstantValue> {
    let mut value = value.trim();
    while value.starts_with('(') && value.ends_with(')') && value.len() > 2 {
        value = &value[1..value.len() - 1];
    }
    let value = value.trim_end_matches(|ch: char| matches!(ch, 'u' | 'U' | 'l' | 'L' | 'f' | 'F'));
    if value.contains(['.', 'e', 'E']) {
        return value.parse::<f64>().ok().map(ConstantValue::F64);
    }
    let (negative, digits) = value
        .strip_prefix('-')
        .map_or((false, value), |rest| (true, rest));
    let parsed = if let Some(hex) = digits
        .strip_prefix("0x")
        .or_else(|| digits.strip_prefix("0X"))
    {
        i64::from_str_radix(hex, 16).ok()
    } else if digits.starts_with('0') && digits.len() > 1 {
        i64::from_str_radix(&digits[1..], 8).ok()
    } else {
        digits.parse::<i64>().ok()
    }?;
    Some(ConstantValue::I64(if negative { -parsed } else { parsed }))
}

fn strip_comments(source: &str) -> Result<String, String> {
    let chars: Vec<char> = source.chars().collect();
    let mut output = String::with_capacity(chars.len());
    let mut index = 0;
    while index < chars.len() {
        if chars[index] == '/' && chars.get(index + 1) == Some(&'/') {
            index += 2;
            while index < chars.len() && chars[index] != '\n' {
                index += 1;
            }
        } else if chars[index] == '/' && chars.get(index + 1) == Some(&'*') {
            index += 2;
            while index + 1 < chars.len() && !(chars[index] == '*' && chars[index + 1] == '/') {
                if chars[index] == '\n' {
                    output.push('\n');
                }
                index += 1;
            }
            if index + 1 >= chars.len() {
                return Err("unterminated block comment in C header".into());
            }
            index += 2;
        } else {
            output.push(chars[index]);
            index += 1;
        }
    }
    Ok(output)
}

fn tokenize(source: &str) -> Result<Vec<String>, String> {
    let chars: Vec<char> = source.chars().collect();
    let mut tokens = Vec::new();
    let mut index = 0;
    while index < chars.len() {
        if chars[index].is_whitespace() {
            index += 1;
        } else if chars[index].is_ascii_alphabetic() || chars[index] == '_' {
            let start = index;
            index += 1;
            while index < chars.len()
                && (chars[index].is_ascii_alphanumeric() || chars[index] == '_')
            {
                index += 1;
            }
            tokens.push(chars[start..index].iter().collect());
        } else if chars[index].is_ascii_digit()
            || (chars[index] == '-'
                && chars
                    .get(index + 1)
                    .is_some_and(|next| next.is_ascii_digit()))
        {
            let start = index;
            index += 1;
            while index < chars.len()
                && (chars[index].is_ascii_alphanumeric() || matches!(chars[index], '.' | '+' | '-'))
            {
                index += 1;
            }
            tokens.push(chars[start..index].iter().collect());
        } else if chars[index] == '"' || chars[index] == '\'' {
            let quote = chars[index];
            let start = index;
            index += 1;
            let mut escaped = false;
            while index < chars.len() {
                let ch = chars[index];
                index += 1;
                if escaped {
                    escaped = false;
                } else if ch == '\\' {
                    escaped = true;
                } else if ch == quote {
                    break;
                }
            }
            if chars.get(index.saturating_sub(1)) != Some(&quote) {
                return Err("unterminated C string or character literal".into());
            }
            tokens.push(chars[start..index].iter().collect());
        } else if chars[index] == '.'
            && chars.get(index + 1) == Some(&'.')
            && chars.get(index + 2) == Some(&'.')
        {
            tokens.push("...".into());
            index += 3;
        } else {
            tokens.push(chars[index].to_string());
            index += 1;
        }
    }
    Ok(tokens)
}

fn split_declarations(tokens: &[String]) -> Vec<Vec<String>> {
    let mut declarations = Vec::new();
    let mut current = Vec::new();
    let mut brace_depth = 0usize;
    for token in tokens {
        match token.as_str() {
            "{" => brace_depth += 1,
            "}" => brace_depth = brace_depth.saturating_sub(1),
            ";" if brace_depth == 0 => {
                declarations.push(std::mem::take(&mut current));
                continue;
            }
            _ => {}
        }
        current.push(token.clone());
    }
    if !current.is_empty() {
        declarations.push(current);
    }
    declarations
}

fn parse_typedef(tokens: &[String], header: &mut Header) {
    let body = &tokens[1..];
    if body.first().is_some_and(|token| token == "enum") {
        let alias = body.last().filter(|token| valid_identifier(token)).cloned();
        if let Some(enumeration) = parse_enum(body, alias.clone()) {
            if let Some(alias) = alias {
                header.aliases.insert(
                    alias.clone(),
                    CType {
                        base: format!("enum {alias}"),
                        ..CType::default()
                    },
                );
            }
            header.enums.push(enumeration);
        }
        return;
    }
    if body
        .first()
        .is_some_and(|token| token == "struct" || token == "union")
    {
        index_struct(body, header);
        if let Some(alias) = body.last().filter(|token| valid_identifier(token)) {
            let tag = body.get(1).filter(|token| valid_identifier(token));
            let base_name = tag.unwrap_or(alias);
            header.aliases.insert(
                alias.clone(),
                CType {
                    base: format!("{} {}", body[0], base_name),
                    ..CType::default()
                },
            );
        }
        return;
    }
    if let Some((name, ty)) = parse_alias(body) {
        header.aliases.insert(name, ty);
    }
}

fn parse_alias(tokens: &[String]) -> Option<(String, CType)> {
    if let Some((name, ty)) = parse_callback_declarator(tokens, 0) {
        return name.map(|name| (name, ty));
    }
    if tokens.iter().any(|token| token == "(") {
        return None;
    }
    let name_index = tokens.iter().rposition(|token| valid_identifier(token))?;
    let name = tokens[name_index].clone();
    let ty = parse_type_tokens(&tokens[..name_index]);
    (!ty.base.is_empty()).then_some((name, ty))
}

fn parse_callback_declarator(
    tokens: &[String],
    parameter_index: usize,
) -> Option<(Option<String>, CType)> {
    // The pointer declarator must be followed immediately by its argument list.
    let open = (0..tokens.len()).find(|index| {
        tokens[*index] == "(" && tokens.get(*index + 1).is_some_and(|token| token == "*")
    })?;
    let declarator_close = matching_close(tokens, open)?;
    let args_open = declarator_close + 1;
    if !tokens.get(args_open).is_some_and(|token| token == "(") {
        return None;
    }
    let args_close = matching_close(tokens, args_open)?;
    if args_close + 1 != tokens.len() {
        return None;
    }
    let name = tokens[open + 2..declarator_close]
        .iter()
        .find(|token| valid_identifier(token))
        .cloned();
    let ret = parse_type_tokens(&tokens[..open]);
    if ret.base.is_empty() {
        return None;
    }
    let mut params = Vec::new();
    let mut variadic = false;
    let slices = split_commas(&tokens[args_open + 1..args_close]);
    if !(slices.len() == 1 && slices[0].len() == 1 && slices[0][0] == "void") {
        for (index, parameter) in slices.into_iter().enumerate() {
            if parameter.len() == 1 && parameter[0] == "..." {
                variadic = true;
            } else if !parameter.is_empty() {
                params.push(parse_parameter(parameter, parameter_index + index));
            }
        }
    }
    Some((
        name,
        CType {
            callback: Some(Box::new(CCallback {
                params,
                ret,
                variadic,
            })),
            ..CType::default()
        },
    ))
}

fn parse_enum(tokens: &[String], alias: Option<String>) -> Option<CEnum> {
    let open = tokens.iter().position(|token| token == "{")?;
    let close = tokens.iter().rposition(|token| token == "}")?;
    let tag = tokens
        .get(1)
        .filter(|token| valid_identifier(token))
        .cloned();
    let name = alias.or(tag)?;
    let mut variants = Vec::new();
    let mut index = open + 1;
    let mut next_value = 0i64;
    while index < close {
        if tokens[index] == "," {
            index += 1;
            continue;
        }
        if !valid_identifier(&tokens[index]) {
            return None;
        }
        let variant = tokens[index].clone();
        index += 1;
        let value = if tokens.get(index).is_some_and(|token| token == "=") {
            index += 1;
            let parsed = tokens
                .get(index)
                .and_then(|token| parse_constant(token))
                .and_then(|constant| match constant {
                    ConstantValue::I64(value) => Some(value),
                    ConstantValue::F64(_) => None,
                })?;
            index += 1;
            parsed
        } else {
            next_value
        };
        variants.push((variant, value));
        next_value = value.saturating_add(1);
        while index < close && tokens[index] != "," {
            index += 1;
        }
    }
    (!variants.is_empty()).then_some(CEnum { name, variants })
}

fn index_struct(tokens: &[String], header: &mut Header) {
    let tag = tokens
        .get(1)
        .filter(|token| valid_identifier(token))
        .cloned();
    let open = tokens.iter().position(|token| token == "{");
    let close = tokens.iter().rposition(|token| token == "}");
    let alias = close
        .and_then(|close| tokens.get(close + 1))
        .filter(|token| valid_identifier(token))
        .cloned();
    let Some(name) = tag.or(alias) else {
        return;
    };
    let fields = match (tokens.first().map(String::as_str), open, close) {
        (Some("struct"), Some(open), Some(close)) if open < close => {
            let mut fields = Vec::new();
            let mut start = open + 1;
            let mut valid = true;
            for end in open + 1..=close {
                if end == close || tokens[end] == ";" {
                    let declaration = &tokens[start..end];
                    if !declaration.is_empty() {
                        if declaration.iter().any(|token| token == "[")
                            || declaration.iter().any(|token| token == ",")
                        {
                            valid = false;
                            break;
                        }
                        fields.push(parse_parameter(declaration, fields.len()));
                    }
                    start = end + 1;
                }
            }
            (valid && !fields.is_empty()).then_some(fields)
        }
        _ => None,
    };
    header
        .structs
        .entry(name)
        .and_modify(|existing| {
            if fields.is_some() {
                *existing = fields.clone();
            }
        })
        .or_insert(fields);
}

fn parse_function(tokens: &[String]) -> Option<CFunction> {
    let open = tokens.iter().position(|token| token == "(")?;
    let close = matching_close(tokens, open)?;
    if close + 1 != tokens.len() || open == 0 {
        return None;
    }
    let name_index = (0..open)
        .rev()
        .find(|index| valid_identifier(&tokens[*index]))?;
    let name = tokens[name_index].clone();
    let ret = parse_type_tokens(&tokens[..name_index]);
    if ret.base.is_empty() {
        return None;
    }
    let mut params = Vec::new();
    let mut variadic = false;
    let slices = split_commas(&tokens[open + 1..close]);
    if !(slices.len() == 1 && slices[0].len() == 1 && slices[0][0] == "void") {
        for (index, parameter) in slices.into_iter().enumerate() {
            if parameter.len() == 1 && parameter[0] == "..." {
                variadic = true;
                continue;
            }
            if parameter.is_empty() {
                continue;
            }
            params.push(parse_parameter(parameter, index));
        }
    }
    Some(CFunction {
        name,
        params,
        ret,
        variadic,
    })
}

fn parse_parameter(tokens: &[String], index: usize) -> CParam {
    if let Some((name, ty)) = parse_callback_declarator(tokens, index) {
        return CParam {
            name: name.unwrap_or_else(|| format!("arg{index}")),
            ty,
            bit_width: None,
        };
    }
    let name_index = tokens
        .iter()
        .rposition(|token| valid_identifier(token) && !is_type_word(token));
    let name = name_index
        .map(|position| tokens[position].clone())
        .unwrap_or_else(|| format!("arg{index}"));
    let type_end = name_index.unwrap_or(tokens.len());
    let mut ty = parse_type_tokens(&tokens[..type_end]);
    if tokens
        .get(type_end + 1..)
        .is_some_and(|tail| tail.iter().any(|token| token == "["))
    {
        ty.pointers += 1;
    }
    let bit_width = tokens
        .iter()
        .position(|token| token == ":")
        .map(|colon| tokens[colon + 1..].join(" "));
    CParam {
        name,
        ty,
        bit_width,
    }
}

fn parse_type_tokens(tokens: &[String]) -> CType {
    let mut ty = CType::default();
    let mut words = Vec::new();
    let mut index = 0;
    while index < tokens.len() {
        match tokens[index].as_str() {
            "*" => ty.pointers += 1,
            "const" | "__const" | "__const__" => ty.is_const = true,
            "volatile" | "restrict" | "__restrict" | "__restrict__" | "extern" | "static"
            | "inline" | "__inline" | "__inline__" => {}
            "__attribute__" | "__declspec" => {
                if tokens.get(index + 1).is_some_and(|token| token == "(") {
                    if let Some(close) = matching_close(tokens, index + 1) {
                        index = close;
                    }
                }
            }
            token => words.push(token.to_string()),
        }
        index += 1;
    }
    ty.base = canonical_base(&words.join(" "));
    ty
}

fn split_commas(tokens: &[String]) -> Vec<&[String]> {
    let mut parts = Vec::new();
    let mut start = 0;
    let mut depth = 0usize;
    for (index, token) in tokens.iter().enumerate() {
        match token.as_str() {
            "(" | "[" | "{" => depth += 1,
            ")" | "]" | "}" => depth = depth.saturating_sub(1),
            "," if depth == 0 => {
                parts.push(&tokens[start..index]);
                start = index + 1;
            }
            _ => {}
        }
    }
    parts.push(&tokens[start..]);
    parts
}

fn matching_close(tokens: &[String], open: usize) -> Option<usize> {
    let pair = match tokens.get(open)?.as_str() {
        "(" => (")", "("),
        "[" => ("]", "["),
        "{" => ("}", "{"),
        _ => return None,
    };
    let mut depth = 0usize;
    for (index, token) in tokens.iter().enumerate().skip(open) {
        if token == pair.1 {
            depth += 1;
        } else if token == pair.0 {
            depth -= 1;
            if depth == 0 {
                return Some(index);
            }
        }
    }
    None
}

fn valid_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    chars
        .next()
        .is_some_and(|first| first.is_ascii_alphabetic() || first == '_')
        && chars.all(|ch| ch.is_ascii_alphanumeric() || ch == '_')
}

fn is_type_word(value: &str) -> bool {
    matches!(
        value,
        "void"
            | "char"
            | "short"
            | "int"
            | "long"
            | "signed"
            | "unsigned"
            | "float"
            | "double"
            | "bool"
            | "_Bool"
            | "const"
            | "volatile"
            | "restrict"
            | "struct"
            | "union"
            | "enum"
            | "int8_t"
            | "int16_t"
            | "int32_t"
            | "int64_t"
            | "uint8_t"
            | "uint16_t"
            | "uint32_t"
            | "uint64_t"
            | "size_t"
            | "ssize_t"
            | "intptr_t"
            | "uintptr_t"
            | "ptrdiff_t"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_safe_functions_constants_and_sequential_enums() {
        let header = r#"
            #define LIMIT 0x10
            #define RATE 0.125
            typedef int64_t index_t;
            typedef enum state { IDLE = 0, BUSY = 1 } state;
            double hypot(double x, double y);
            int64_t count(index_t n);
        "#;
        let generated = generate(header, Path::new("sample.h"), "m", None).unwrap();
        assert!(generated.source.contains("fn LIMIT(): i64"));
        assert!(generated.source.contains("fn RATE(): f64"));
        assert!(generated.source.contains("enum state"));
        assert!(generated
            .source
            .contains("extern \"m\" fn hypot(x: f64, y: f64): f64"));
        assert!(generated
            .source
            .contains("extern \"m\" fn count(n: i64): i64"));
        assert_eq!(generated.imported_functions, 2);
    }

    #[test]
    fn imports_f32_callbacks_and_refuses_other_inexact_boundary_representations() {
        let header = r#"
            float narrow(float x);
            int ordinary_int(int x);
            void *allocate(size_t size);
            int64_t callback(int64_t (*f)(int64_t));
        "#;
        let generated = generate(header, Path::new("unsafe.h"), "unsafe", None).unwrap();
        assert_eq!(generated.imported_functions, 2);
        assert!(generated
            .source
            .contains("extern \"unsafe\" fn narrow(x: f32): f32"));
        assert!(generated
            .warnings
            .iter()
            .any(|warning| warning.contains("size_t")));
        assert!(generated
            .source
            .contains("extern \"unsafe\" fn callback(f: c_fn[(i64)->i64]): i64"));
    }

    #[test]
    fn resolves_callback_typedef_parameters_and_returns() {
        let header = r#"
            typedef int64_t (*transform_fn)(int64_t, double);
            transform_fn install_transform(transform_fn callback);
        "#;
        let generated = generate(header, Path::new("callbacks.h"), "callbacks", None).unwrap();
        assert_eq!(generated.imported_functions, 1);
        assert!(generated.source.contains(
            "extern \"callbacks\" fn install_transform(callback: c_fn[(i64,f64)->i64]): c_fn[(i64,f64)->i64]"
        ));
    }

    #[test]
    fn imports_portable_returns_union_handles_and_shims_bitfields() {
        let header = r#"
            typedef struct pair { int64_t x; int64_t y; } pair;
            typedef struct flags { unsigned int mode : 3; int enabled : 1; } flags;
            typedef union value { int64_t integer; double real; } value;
            pair make_pair(int64_t x, int64_t y);
            int64_t read_flags(flags value);
            int64_t inspect_value(const value *value);
        "#;
        let generated = generate(
            header,
            Path::new("aggregates.h"),
            "aggregates",
            Some("shim"),
        )
        .unwrap();
        assert!(generated
            .source
            .contains("extern \"aggregates\" fn make_pair(x: i64, y: i64): pair"));
        assert!(generated.source.contains("type flags"));
        assert!(!generated.source.contains("@c_layout type flags"));
        assert!(generated
            .source
            .contains("fn read_flags(value: flags): i64"));
        assert!(generated
            .source
            .contains("inspect_value(value: c_ptr[value]): i64"));
        assert_eq!(generated.shimmed_functions, 1);
    }
}
