// LLVM AOT backend for `lu build`: emit textual LLVM IR, hand it to clang.
//
// Language semantics become IR facts:
//  - every FP op carries the `fast` flag (approximate-FP-by-contract) — LLVM may
//    reassociate, contract, and vectorize reductions;
//  - math functions are declared `memory(none)`, so LICM hoists loop-invariant
//    calls (the win the JIT tier can't get from Cranelift);
//  - loop-range bounds checks are hoisted by the same trusted-index scan the JIT
//    uses, leaving check-free hot loops for the vectorizer.
use crate::ast::*;
use crate::check::{resolve_type, Type as CType};
use crate::jit::{field_offset, scan_trusted, scan_trusted_expr};
use std::collections::HashMap;
use std::fmt::Write as _;

const RTOL: f64 = 9.094947017729282e-13; // 2^-40
const ATOL: f64 = 7.888609052210118e-31; // 2^-100

fn lty(p: &Program, t: &CType) -> Result<Vec<&'static str>, String> {
    Ok(match t {
        CType::F64 => vec!["double"],
        CType::I64 | CType::Bool => vec!["i64"],
        CType::Str => vec!["ptr", "i64"],
        CType::Arr(_) => vec!["ptr"],
        CType::Unit => vec![],
        CType::Rec(ti) => {
            let mut out = Vec::new();
            for (_, ft) in &p.types[*ti].fields {
                out.extend(lty(p, &resolve_type(p, ft)?)?);
            }
            out
        }
    })
}

fn ret_ty(p: &Program, t: &CType) -> Result<String, String> {
    let c = lty(p, t)?;
    Ok(match c.len() {
        0 => "void".into(),
        1 => c[0].into(),
        _ => format!("{{ {} }}", c.join(", ")),
    })
}

#[derive(Clone)]
struct EV {
    ty: CType,
    regs: Vec<String>, // literal constants or %regs, one per component
}

struct Emit<'a> {
    p: &'a Program,
    out: String,
    tmp: u32,
    lbl: u32,
    // name -> (type, alloca ptrs per component)
    env: Vec<HashMap<String, (CType, Vec<String>)>>,
    strings: Vec<String>,
    trusted: Vec<(String, String)>,
    ret: CType,
    terminated: bool,
}

pub fn build(p: &Program, src_path: &str, out_path: Option<&str>) -> Result<String, String> {
    let mut e = Emit {
        p,
        out: String::new(),
        tmp: 0,
        lbl: 0,
        env: vec![HashMap::new()],
        strings: Vec::new(),
        trusted: Vec::new(),
        ret: CType::Unit,
        terminated: false,
    };
    let mut module = String::new();
    module.push_str("; generated by lu\n");
    // Ask clang for the triple it actually stamps on compiled modules (the
    // driver maps e.g. darwin25 -> macosx26 per deployment target, so
    // -print-target-triple alone is not what IR modules carry).
    let probe = std::process::Command::new("clang")
        .args(["-x", "c", "-", "-S", "-emit-llvm", "-o", "-"])
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::null())
        .spawn()
        .and_then(|mut c| {
            use std::io::Write as _;
            c.stdin.take().unwrap().write_all(b"int lu_probe;\n")?;
            c.wait_with_output()
        })
        .map_err(|e| format!("failed to probe clang target triple: {}", e))?;
    let triple = String::from_utf8_lossy(&probe.stdout)
        .lines()
        .find_map(|l| l.strip_prefix("target triple = \"").map(|r| r.trim_end_matches('"').to_string()))
        .ok_or("could not determine target triple from clang")?;
    let _ = writeln!(module, "target triple = \"{}\"", triple);
    module.push_str(
        "declare double @llvm.sqrt.f64(double)\ndeclare double @llvm.sin.f64(double)\n\
         declare double @llvm.cos.f64(double)\ndeclare double @llvm.fabs.f64(double)\n\
         declare double @llvm.floor.f64(double)\ndeclare double @llvm.minnum.f64(double, double)\n\
         declare double @llvm.maxnum.f64(double, double)\ndeclare double @llvm.pow.f64(double, double)\n\
         declare double @acos(double) #0\ndeclare double @atan2(double, double) #0\n\
         declare void @lu_print_f64(double)\ndeclare void @lu_print_i64(i64)\n\
         declare void @lu_print_bool(i64)\ndeclare void @lu_print_str(ptr, i64)\n\
         declare void @lu_print_sep()\ndeclare void @lu_print_nl()\n\
         declare ptr @lu_arr_new_f64(i64, double)\ndeclare ptr @lu_arr_new_i64(i64, i64)\n\
         declare void @lu_oob(i64, i64) #1\n\
         attributes #0 = { nounwind willreturn memory(none) }\n\
         attributes #1 = { noreturn }\n\n",
    );
    for f in &p.fns {
        module.push_str(&e.emit_fn(f)?);
    }
    let main = p.main.as_ref().ok_or("no `main` block in program")?;
    module.push_str(&e.emit_main(main)?);
    for (i, s) in e.strings.iter().enumerate() {
        let bytes: String = s.bytes().map(|b| format!("\\{:02X}", b)).collect();
        let _ = writeln!(
            module,
            "@.str.{} = private unnamed_addr constant [{} x i8] c\"{}\"",
            i,
            s.len(),
            bytes
        );
    }

    // write .ll and compile with clang
    let stem = std::path::Path::new(src_path)
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("out");
    let out_bin = out_path.map(String::from).unwrap_or_else(|| stem.to_string());
    let ll_path = std::env::temp_dir().join(format!("lu_{}.ll", stem));
    std::fs::write(&ll_path, &module).map_err(|e| e.to_string())?;
    // compile the runtime once per source revision, then just link the object
    let rt_src = include_str!("lu_runtime.c");
    let rt_hash: u64 = rt_src.bytes().fold(1469598103934665603u64, |h, b| {
        (h ^ b as u64).wrapping_mul(1099511628211)
    });
    let runtime_o = std::env::temp_dir().join(format!("lu_runtime_{:016x}.o", rt_hash));
    if !runtime_o.exists() {
        let runtime_c = std::env::temp_dir().join("lu_runtime.c");
        std::fs::write(&runtime_c, rt_src).map_err(|e| e.to_string())?;
        let st = std::process::Command::new("clang")
            .args(["-O3", "-mcpu=native", "-c", "-o"])
            .arg(&runtime_o)
            .arg(&runtime_c)
            .status()
            .map_err(|e| format!("failed to invoke clang: {}", e))?;
        if !st.success() {
            return Err("clang failed compiling the runtime".into());
        }
    }
    let status = std::process::Command::new("clang")
        .args(["-O3", "-mcpu=native", "-o", &out_bin])
        .arg(&ll_path)
        .arg(&runtime_o)
        .status()
        .map_err(|e| format!("failed to invoke clang: {}", e))?;
    if !status.success() {
        return Err(format!("clang failed on {}", ll_path.display()));
    }
    Ok(out_bin)
}

impl<'a> Emit<'a> {
    fn t(&mut self) -> String {
        self.tmp += 1;
        format!("%t{}", self.tmp)
    }
    fn l(&mut self) -> String {
        self.lbl += 1;
        format!("L{}", self.lbl)
    }
    fn line(&mut self, s: String) {
        self.out.push_str("  ");
        self.out.push_str(&s);
        self.out.push('\n');
    }
    fn label(&mut self, l: &str) {
        self.out.push_str(l);
        self.out.push_str(":\n");
    }

    fn emit_fn(&mut self, f: &FnDecl) -> Result<String, String> {
        self.out = String::new();
        self.tmp = 0;
        self.lbl = 0;
        self.env = vec![HashMap::new()];
        self.trusted.clear();
        self.terminated = false;
        self.ret = resolve_type(self.p, &f.ret)?;

        let mut params = Vec::new();
        let mut binds = Vec::new();
        let mut idx = 0;
        for (name, tstr) in &f.params {
            let t = resolve_type(self.p, tstr)?;
            let mut regs = Vec::new();
            for c in lty(self.p, &t)? {
                params.push(format!("{} %p{}", c, idx));
                regs.push(format!("%p{}", idx));
                idx += 1;
            }
            binds.push((name.clone(), t, regs));
        }
        let rt = ret_ty(self.p, &self.ret)?;
        let header = format!("define internal {} @\"{}\"({}) {{\n", rt, f.name, params.join(", "));
        self.label("entry");
        for (name, t, regs) in binds {
            self.declare(&name, &t, &regs)?;
        }
        let last = self.emit_block(&f.body)?;
        if !self.terminated {
            match last {
                Some(v) if v.ty == self.ret => self.emit_ret(&v)?,
                _ if self.ret == CType::Unit => self.line("ret void".into()),
                _ => return Err(format!("function `{}` may end without a value", f.name)),
            }
        }
        Ok(format!("{}{}}}\n\n", header, self.out))
    }

    fn emit_main(&mut self, body: &[StmtId]) -> Result<String, String> {
        self.out = String::new();
        self.tmp = 0;
        self.lbl = 0;
        self.env = vec![HashMap::new()];
        self.trusted.clear();
        self.terminated = false;
        self.ret = CType::Unit;
        self.label("entry");
        self.emit_block(body)?;
        if !self.terminated {
            self.line("ret i32 0".into());
        }
        Ok(format!("define i32 @main() {{\n{}}}\n\n", self.out))
    }

    fn emit_ret(&mut self, v: &EV) -> Result<(), String> {
        let comps = lty(self.p, &v.ty)?;
        match comps.len() {
            0 => self.line("ret void".into()),
            1 => self.line(format!("ret {} {}", comps[0], v.regs[0])),
            _ => {
                let sty = ret_ty(self.p, &v.ty)?;
                let mut cur = "undef".to_string();
                for (i, (c, r)) in comps.iter().zip(v.regs.iter()).enumerate() {
                    let t = self.t();
                    self.line(format!("{} = insertvalue {} {}, {} {}, {}", t, sty, cur, c, r, i));
                    cur = t;
                }
                self.line(format!("ret {} {}", sty, cur));
            }
        }
        self.terminated = true;
        Ok(())
    }

    fn declare(&mut self, name: &str, t: &CType, regs: &[String]) -> Result<(), String> {
        let mut ptrs = Vec::new();
        for (i, c) in lty(self.p, t)?.iter().enumerate() {
            let a = self.t();
            self.line(format!("{} = alloca {}", a, c));
            self.line(format!("store {} {}, ptr {}", c, regs[i], a));
            ptrs.push(a);
        }
        self.env.last_mut().unwrap().insert(name.to_string(), (t.clone(), ptrs));
        Ok(())
    }

    fn lookup(&self, name: &str) -> Option<(CType, Vec<String>)> {
        self.env.iter().rev().find_map(|s| s.get(name).cloned())
    }

    fn load_var(&mut self, name: &str) -> Result<EV, String> {
        let (t, ptrs) = self.lookup(name).ok_or(format!("unknown variable `{}`", name))?;
        let comps = lty(self.p, &t)?;
        let mut regs = Vec::new();
        for (c, ptr) in comps.iter().zip(ptrs.iter()) {
            let r = self.t();
            self.line(format!("{} = load {}, ptr {}", r, c, ptr));
            regs.push(r);
        }
        Ok(EV { ty: t, regs })
    }

    fn store_var(&mut self, name: &str, v: &EV) -> Result<(), String> {
        let (t, ptrs) = self.lookup(name).ok_or(format!("unknown variable `{}`", name))?;
        let comps = lty(self.p, &t)?;
        for ((c, ptr), r) in comps.iter().zip(ptrs.iter()).zip(v.regs.iter()) {
            self.line(format!("store {} {}, ptr {}", c, r, ptr));
        }
        Ok(())
    }

    fn to_f64(&mut self, v: &EV) -> Result<String, String> {
        if v.ty == CType::I64 {
            let t = self.t();
            self.line(format!("{} = sitofp i64 {} to double", t, v.regs[0]));
            Ok(t)
        } else {
            Ok(v.regs[0].clone())
        }
    }

    fn emit_block(&mut self, stmts: &[StmtId]) -> Result<Option<EV>, String> {
        self.env.push(HashMap::new());
        let mut last = None;
        for &sid in stmts {
            if self.terminated {
                break;
            }
            last = self.emit_stmt(sid)?;
        }
        self.env.pop();
        Ok(last)
    }

    fn emit_stmt(&mut self, sid: StmtId) -> Result<Option<EV>, String> {
        match self.p.stmt(sid) {
            Stmt::Let(n, e) | Stmt::Var(n, e) => {
                let v = self.emit_expr(*e)?;
                let regs = v.regs.clone();
                self.declare(n, &v.ty, &regs)?;
                Ok(None)
            }
            Stmt::Assign(target, e) => {
                let v = self.emit_expr(*e)?;
                match self.p.expr(*target) {
                    Expr::Ident(n) => self.store_var(n, &v)?,
                    Expr::Index(a, i) => {
                        let trusted = self.is_trusted(*a, *i);
                        let av = self.emit_expr(*a)?;
                        let iv = self.emit_expr(*i)?;
                        let elem = match &av.ty {
                            CType::Arr(e) => e.as_ref().clone(),
                            _ => return Err("cannot index non-array".into()),
                        };
                        let addr = self.index_addr(&av.regs[0], &iv.regs[0], &elem, trusted)?;
                        let comps = lty(self.p, &elem)?;
                        for (k, (c, r)) in comps.iter().zip(v.regs.iter()).enumerate() {
                            let ep = self.t();
                            self.line(format!("{} = getelementptr i8, ptr {}, i64 {}", ep, addr, k * 8));
                            self.line(format!("store {} {}, ptr {}", c, r, ep));
                        }
                    }
                    _ => return Err("invalid assignment target".into()),
                }
                Ok(None)
            }
            Stmt::If(c, then_s, else_s) => {
                let cv = self.emit_expr(*c)?;
                let cb = self.t();
                self.line(format!("{} = icmp ne i64 {}, 0", cb, cv.regs[0]));
                let lt = self.l();
                let le = self.l();
                let lm = self.l();
                self.line(format!("br i1 {}, label %{}, label %{}", cb, lt, le));
                self.label(&lt);
                self.terminated = false;
                self.emit_block(then_s)?;
                let t_term = self.terminated;
                if !t_term {
                    self.line(format!("br label %{}", lm));
                }
                self.label(&le);
                self.terminated = false;
                self.emit_block(else_s)?;
                let e_term = self.terminated;
                if !e_term {
                    self.line(format!("br label %{}", lm));
                }
                if t_term && e_term {
                    self.terminated = true;
                    Ok(None)
                } else {
                    self.label(&lm);
                    self.terminated = false;
                    Ok(None)
                }
            }
            Stmt::For(v, lo, hi, body) => {
                let lov = self.emit_expr(*lo)?;
                let hiv = self.emit_expr(*hi)?;
                let pushed = match scan_trusted(self.p, body, v) {
                    Some(arrays) => self.hoist_checks(&arrays, v, &lov.regs[0], &hiv.regs[0])?,
                    None => 0,
                };
                let iptr = self.t();
                self.line(format!("{} = alloca i64", iptr));
                self.line(format!("store i64 {}, ptr {}", lov.regs[0], iptr));
                self.env.push(HashMap::new());
                self.env
                    .last_mut()
                    .unwrap()
                    .insert(v.clone(), (CType::I64, vec![iptr.clone()]));
                let lh = self.l();
                let lb = self.l();
                let lx = self.l();
                self.line(format!("br label %{}", lh));
                self.label(&lh);
                let iv = self.t();
                self.line(format!("{} = load i64, ptr {}", iv, iptr));
                let cnd = self.t();
                self.line(format!("{} = icmp slt i64 {}, {}", cnd, iv, hiv.regs[0]));
                self.line(format!("br i1 {}, label %{}, label %{}", cnd, lb, lx));
                self.label(&lb);
                self.emit_block(body)?;
                if !self.terminated {
                    let iv2 = self.t();
                    self.line(format!("{} = load i64, ptr {}", iv2, iptr));
                    let nx = self.t();
                    self.line(format!("{} = add i64 {}, 1", nx, iv2));
                    self.line(format!("store i64 {}, ptr {}", nx, iptr));
                    self.line(format!("br label %{}", lh));
                }
                self.terminated = false;
                self.label(&lx);
                self.env.pop();
                self.trusted.truncate(self.trusted.len() - pushed);
                Ok(None)
            }
            Stmt::Return(e) => {
                let v = match e {
                    Some(e) => Some(self.emit_expr(*e)?),
                    None => None,
                };
                match v {
                    Some(v) => {
                        // promote int literal returns into float fns
                        let v = if self.ret == CType::F64 && v.ty == CType::I64 {
                            let r = self.to_f64(&v)?;
                            EV { ty: CType::F64, regs: vec![r] }
                        } else {
                            v
                        };
                        self.emit_ret(&v)?
                    }
                    None => {
                        if self.ret == CType::Unit {
                            self.line("ret void".into());
                            self.terminated = true;
                        }
                    }
                }
                Ok(None)
            }
            Stmt::Expr(e) => Ok(Some(self.emit_expr(*e)?)),
        }
    }

    fn is_trusted(&self, a: ExprId, i: ExprId) -> bool {
        if let (Expr::Ident(an), Expr::Ident(inm)) = (self.p.expr(a), self.p.expr(i)) {
            self.trusted.iter().any(|(x, y)| x == an && y == inm)
        } else {
            false
        }
    }

    fn hoist_checks(&mut self, arrays: &[String], var: &str, lo: &str, hi: &str) -> Result<usize, String> {
        let mut pushed = 0;
        for name in arrays {
            let Some((CType::Arr(elem), ptrs)) = self.lookup(name) else { continue };
            let stride = lty(self.p, &elem)?.len() as i64;
            let base = self.t();
            self.line(format!("{} = load ptr, ptr {}", base, ptrs[0]));
            let lenr = self.t();
            self.line(format!("{} = load i64, ptr {}", lenr, base));
            let logical = if stride == 1 {
                lenr.clone()
            } else {
                let d = self.t();
                self.line(format!("{} = sdiv i64 {}, {}", d, lenr, stride));
                d
            };
            let neg = self.t();
            self.line(format!("{} = icmp slt i64 {}, 0", neg, lo));
            let over = self.t();
            self.line(format!("{} = icmp sgt i64 {}, {}", over, hi, logical));
            let bad = self.t();
            self.line(format!("{} = or i1 {}, {}", bad, neg, over));
            let lb = self.l();
            let lg = self.l();
            self.line(format!("br i1 {}, label %{}, label %{}", bad, lb, lg));
            self.label(&lb);
            self.line(format!("call void @lu_oob(i64 {}, i64 {})", hi, logical));
            self.line("unreachable".into());
            self.label(&lg);
            self.trusted.push((name.clone(), var.to_string()));
            pushed += 1;
        }
        Ok(pushed)
    }

    fn index_addr(&mut self, base: &str, idx: &str, elem: &CType, trusted: bool) -> Result<String, String> {
        let stride = lty(self.p, elem)?.len() as i64;
        if !trusted {
            let lenr = self.t();
            self.line(format!("{} = load i64, ptr {}", lenr, base));
            let logical = if stride == 1 {
                lenr.clone()
            } else {
                let d = self.t();
                self.line(format!("{} = sdiv i64 {}, {}", d, lenr, stride));
                d
            };
            let bad = self.t();
            self.line(format!("{} = icmp uge i64 {}, {}", bad, idx, logical));
            let lb = self.l();
            let lg = self.l();
            self.line(format!("br i1 {}, label %{}, label %{}", bad, lb, lg));
            self.label(&lb);
            self.line(format!("call void @lu_oob(i64 {}, i64 {})", idx, logical));
            self.line("unreachable".into());
            self.label(&lg);
        }
        let off = self.t();
        self.line(format!("{} = mul i64 {}, {}", off, idx, stride * 8));
        let off8 = self.t();
        self.line(format!("{} = add i64 {}, 8", off8, off));
        let addr = self.t();
        self.line(format!("{} = getelementptr i8, ptr {}, i64 {}", addr, base, off8));
        Ok(addr)
    }

    fn emit_expr(&mut self, eid: ExprId) -> Result<EV, String> {
        match self.p.expr(eid) {
            Expr::Int(v) => Ok(EV { ty: CType::I64, regs: vec![v.to_string()] }),
            Expr::Float(v) => {
                let bits = v.to_bits();
                Ok(EV { ty: CType::F64, regs: vec![format!("0x{:016X}", bits)] })
            }
            Expr::Bool(v) => Ok(EV { ty: CType::Bool, regs: vec![(*v as i64).to_string()] }),
            Expr::Str(s) => {
                let id = self.strings.iter().position(|x| x == s).unwrap_or_else(|| {
                    self.strings.push(s.clone());
                    self.strings.len() - 1
                });
                Ok(EV {
                    ty: CType::Str,
                    regs: vec![format!("@.str.{}", id), s.len().to_string()],
                })
            }
            Expr::Ident(n) => self.load_var(n),
            Expr::Un(op, e) => {
                let v = self.emit_expr(*e)?;
                let t = self.t();
                match (op.as_str(), &v.ty) {
                    ("-", CType::F64) => self.line(format!("{} = fneg fast double {}", t, v.regs[0])),
                    ("-", CType::I64) => self.line(format!("{} = sub i64 0, {}", t, v.regs[0])),
                    ("not", CType::Bool) => self.line(format!("{} = xor i64 {}, 1", t, v.regs[0])),
                    _ => return Err(format!("cannot apply `{}` here", op)),
                }
                Ok(EV { ty: v.ty, regs: vec![t] })
            }
            Expr::Bin(op, l, r) => self.emit_bin(op.clone(), *l, *r),
            Expr::Circum(open, e) => {
                let fname = self.p.circum_ops[open].1.clone();
                let v = self.emit_expr(*e)?;
                self.emit_user_call(&fname, vec![v])
            }
            Expr::Field(e, fname) => {
                let v = self.emit_expr(*e)?;
                match v.ty {
                    CType::Rec(ti) => {
                        let (off, ft) = field_offset(self.p, ti, fname)?;
                        let w = lty(self.p, &ft)?.len();
                        Ok(EV { ty: ft, regs: v.regs[off..off + w].to_vec() })
                    }
                    _ => Err(format!("cannot access field `{}`", fname)),
                }
            }
            Expr::Index(a, i) => {
                let trusted = self.is_trusted(*a, *i);
                let av = self.emit_expr(*a)?;
                let iv = self.emit_expr(*i)?;
                let elem = match &av.ty {
                    CType::Arr(e) => e.as_ref().clone(),
                    _ => return Err("cannot index non-array".into()),
                };
                let addr = self.index_addr(&av.regs[0], &iv.regs[0], &elem, trusted)?;
                let comps = lty(self.p, &elem)?;
                let mut regs = Vec::new();
                for (k, c) in comps.iter().enumerate() {
                    let ep = self.t();
                    self.line(format!("{} = getelementptr i8, ptr {}, i64 {}", ep, addr, k * 8));
                    let r = self.t();
                    self.line(format!("{} = load {}, ptr {}", r, c, ep));
                    regs.push(r);
                }
                Ok(EV { ty: elem, regs })
            }
            Expr::Array(_) => Err("array literals are not supported by AOT yet (use arr)".into()),
            Expr::Record(name, inits) => {
                let ti = self
                    .p
                    .types
                    .iter()
                    .position(|t| t.name == *name)
                    .ok_or(format!("unknown type `{}`", name))?;
                let decl = &self.p.types[ti];
                let nfields = decl.fields.len();
                let mut slots: Vec<Option<Vec<String>>> = vec![None; nfields];
                for (pos, (fname, e)) in inits.iter().enumerate() {
                    let idx = match fname {
                        Some(f) => decl.fields.iter().position(|(n, _)| n == f).unwrap(),
                        None => pos,
                    };
                    let want = resolve_type(self.p, &decl.fields[idx].1)?;
                    let v = self.emit_expr(*e)?;
                    let regs = if want == CType::F64 && v.ty == CType::I64 {
                        vec![self.to_f64(&v)?]
                    } else {
                        v.regs
                    };
                    slots[idx] = Some(regs);
                }
                let mut regs = Vec::new();
                for s in slots {
                    regs.extend(s.expect("checker guarantees all fields"));
                }
                Ok(EV { ty: CType::Rec(ti), regs })
            }
            Expr::Sum { var, lo, hi, body } => {
                let lov = self.emit_expr(*lo)?;
                let hiv = self.emit_expr(*hi)?;
                let scan = {
                    let mut arrays = Vec::new();
                    let mut ok = true;
                    scan_trusted_expr(self.p, *body, var, &mut arrays, &mut ok);
                    if ok && !arrays.is_empty() {
                        Some(arrays)
                    } else {
                        None
                    }
                };
                let pushed = match scan {
                    Some(arrays) => self.hoist_checks(&arrays, var, &lov.regs[0], &hiv.regs[0])?,
                    None => 0,
                };
                let iptr = self.t();
                self.line(format!("{} = alloca i64", iptr));
                self.line(format!("store i64 {}, ptr {}", lov.regs[0], iptr));
                let accp = self.t();
                self.line(format!("{} = alloca double", accp));
                self.line(format!("store double 0.0, ptr {}", accp));
                self.env.push(HashMap::new());
                self.env
                    .last_mut()
                    .unwrap()
                    .insert(var.clone(), (CType::I64, vec![iptr.clone()]));
                let lh = self.l();
                let lb = self.l();
                let lx = self.l();
                self.line(format!("br label %{}", lh));
                self.label(&lh);
                let iv = self.t();
                self.line(format!("{} = load i64, ptr {}", iv, iptr));
                let cnd = self.t();
                self.line(format!("{} = icmp slt i64 {}, {}", cnd, iv, hiv.regs[0]));
                self.line(format!("br i1 {}, label %{}, label %{}", cnd, lb, lx));
                self.label(&lb);
                let bv = self.emit_expr(*body)?;
                let bty = bv.ty.clone();
                let f = self.to_f64(&bv)?;
                let cur = self.t();
                self.line(format!("{} = load double, ptr {}", cur, accp));
                let nx = self.t();
                self.line(format!("{} = fadd fast double {}, {}", nx, cur, f));
                self.line(format!("store double {}, ptr {}", nx, accp));
                let iv2 = self.t();
                self.line(format!("{} = load i64, ptr {}", iv2, iptr));
                let nxt = self.t();
                self.line(format!("{} = add i64 {}, 1", nxt, iv2));
                self.line(format!("store i64 {}, ptr {}", nxt, iptr));
                self.line(format!("br label %{}", lh));
                self.label(&lx);
                self.env.pop();
                self.trusted.truncate(self.trusted.len() - pushed);
                let total = self.t();
                self.line(format!("{} = load double, ptr {}", total, accp));
                if bty == CType::I64 {
                    let ti = self.t();
                    self.line(format!("{} = fptosi double {} to i64", ti, total));
                    Ok(EV { ty: CType::I64, regs: vec![ti] })
                } else {
                    Ok(EV { ty: CType::F64, regs: vec![total] })
                }
            }
            Expr::Call(name, args) => {
                let vs: Result<Vec<EV>, String> = args.iter().map(|&a| self.emit_expr(a)).collect();
                self.emit_call(name, vs?)
            }
        }
    }

    fn emit_bin(&mut self, op: String, l: ExprId, r: ExprId) -> Result<EV, String> {
        if self.p.infix_ops.contains_key(&op) {
            let fname = self.p.infix_ops[&op].clone();
            let lv = self.emit_expr(l)?;
            let rv = self.emit_expr(r)?;
            return self.emit_user_call(&fname, vec![lv, rv]);
        }
        let lv = self.emit_expr(l)?;
        let rv = self.emit_expr(r)?;
        match op.as_str() {
            "and" | "or" => {
                let t = self.t();
                let o = if op == "and" { "and" } else { "or" };
                self.line(format!("{} = {} i64 {}, {}", t, o, lv.regs[0], rv.regs[0]));
                Ok(EV { ty: CType::Bool, regs: vec![t] })
            }
            "+" | "-" | "*" | "/" | "%" => {
                if lv.ty == CType::I64 && rv.ty == CType::I64 {
                    let o = match op.as_str() {
                        "+" => "add",
                        "-" => "sub",
                        "*" => "mul",
                        "/" => "sdiv",
                        _ => "srem",
                    };
                    let t = self.t();
                    self.line(format!("{} = {} i64 {}, {}", t, o, lv.regs[0], rv.regs[0]));
                    Ok(EV { ty: CType::I64, regs: vec![t] })
                } else {
                    let a = self.to_f64(&lv)?;
                    let b = self.to_f64(&rv)?;
                    let o = match op.as_str() {
                        "+" => "fadd",
                        "-" => "fsub",
                        "*" => "fmul",
                        "/" => "fdiv",
                        _ => return Err("`%` on floats is not supported yet".into()),
                    };
                    let t = self.t();
                    self.line(format!("{} = {} fast double {}, {}", t, o, a, b));
                    Ok(EV { ty: CType::F64, regs: vec![t] })
                }
            }
            "==" | "!=" | "<" | "<=" | ">" | ">=" => {
                let both_int = matches!(lv.ty, CType::I64 | CType::Bool)
                    && matches!(rv.ty, CType::I64 | CType::Bool);
                let c1 = self.t();
                if both_int {
                    let cc = match op.as_str() {
                        "==" => "eq",
                        "!=" => "ne",
                        "<" => "slt",
                        "<=" => "sle",
                        ">" => "sgt",
                        _ => "sge",
                    };
                    self.line(format!("{} = icmp {} i64 {}, {}", c1, cc, lv.regs[0], rv.regs[0]));
                } else {
                    let a = self.to_f64(&lv)?;
                    let b = self.to_f64(&rv)?;
                    let cc = match op.as_str() {
                        "==" => "oeq",
                        "!=" => "une",
                        "<" => "olt",
                        "<=" => "ole",
                        ">" => "ogt",
                        _ => "oge",
                    };
                    self.line(format!("{} = fcmp fast {} double {}, {}", c1, cc, a, b));
                }
                let t = self.t();
                self.line(format!("{} = zext i1 {} to i64", t, c1));
                Ok(EV { ty: CType::Bool, regs: vec![t] })
            }
            "~=" | "\u{2248}" => {
                let a = self.to_f64(&lv)?;
                let b = self.to_f64(&rv)?;
                let d = self.t();
                self.line(format!("{} = fsub fast double {}, {}", d, a, b));
                let ad = self.t();
                self.line(format!("{} = call fast double @llvm.fabs.f64(double {})", ad, d));
                let aa = self.t();
                self.line(format!("{} = call fast double @llvm.fabs.f64(double {})", aa, a));
                let ab = self.t();
                self.line(format!("{} = call fast double @llvm.fabs.f64(double {})", ab, b));
                let mx = self.t();
                self.line(format!(
                    "{} = call fast double @llvm.maxnum.f64(double {}, double {})",
                    mx, aa, ab
                ));
                let sc = self.t();
                self.line(format!(
                    "{} = fmul fast double {}, 0x{:016X}",
                    sc,
                    mx,
                    RTOL.to_bits()
                ));
                let tol = self.t();
                self.line(format!(
                    "{} = fadd fast double {}, 0x{:016X}",
                    tol,
                    sc,
                    ATOL.to_bits()
                ));
                let c1 = self.t();
                self.line(format!("{} = fcmp fast ole double {}, {}", c1, ad, tol));
                let t = self.t();
                self.line(format!("{} = zext i1 {} to i64", t, c1));
                Ok(EV { ty: CType::Bool, regs: vec![t] })
            }
            op => Err(format!("unknown operator `{}`", op)),
        }
    }

    fn emit_user_call(&mut self, fname: &str, args: Vec<EV>) -> Result<EV, String> {
        let decl = self
            .p
            .fns
            .iter()
            .find(|f| f.name == fname)
            .ok_or(format!("unknown function `{}`", fname))?;
        let ret = resolve_type(self.p, &decl.ret)?;
        let mut parts = Vec::new();
        for ((_, tstr), v) in decl.params.iter().zip(args) {
            let want = resolve_type(self.p, tstr)?;
            let regs = if want == CType::F64 && v.ty == CType::I64 {
                vec![self.to_f64(&v)?]
            } else {
                v.regs
            };
            for (c, r) in lty(self.p, &want)?.iter().zip(regs.iter()) {
                parts.push(format!("{} {}", c, r));
            }
        }
        let rt = ret_ty(self.p, &ret)?;
        let comps = lty(self.p, &ret)?;
        if comps.is_empty() {
            self.line(format!("call void @\"{}\"({})", fname, parts.join(", ")));
            return Ok(EV { ty: CType::Unit, regs: vec![] });
        }
        let c = self.t();
        self.line(format!("{} = call {} @\"{}\"({})", c, rt, fname, parts.join(", ")));
        if comps.len() == 1 {
            Ok(EV { ty: ret, regs: vec![c] })
        } else {
            let mut regs = Vec::new();
            for i in 0..comps.len() {
                let r = self.t();
                self.line(format!("{} = extractvalue {} {}, {}", r, rt, c, i));
                regs.push(r);
            }
            Ok(EV { ty: ret, regs })
        }
    }

    fn emit_call(&mut self, name: &str, args: Vec<EV>) -> Result<EV, String> {
        match name {
            "print" => {
                for (i, v) in args.iter().enumerate() {
                    if i > 0 {
                        self.line("call void @lu_print_sep()".into());
                    }
                    match &v.ty {
                        CType::F64 => self.line(format!("call void @lu_print_f64(double {})", v.regs[0])),
                        CType::I64 => self.line(format!("call void @lu_print_i64(i64 {})", v.regs[0])),
                        CType::Bool => self.line(format!("call void @lu_print_bool(i64 {})", v.regs[0])),
                        CType::Str => self.line(format!(
                            "call void @lu_print_str(ptr {}, i64 {})",
                            v.regs[0], v.regs[1]
                        )),
                        t => return Err(format!("cannot print {:?} in AOT yet", t)),
                    }
                }
                self.line("call void @lu_print_nl()".into());
                Ok(EV { ty: CType::Unit, regs: vec![] })
            }
            "sqrt" | "sin" | "cos" | "abs" | "floor" => {
                let x = self.to_f64(&args[0])?;
                let intr = match name {
                    "sqrt" => "llvm.sqrt.f64",
                    "sin" => "llvm.sin.f64",
                    "cos" => "llvm.cos.f64",
                    "abs" => "llvm.fabs.f64",
                    _ => "llvm.floor.f64",
                };
                let t = self.t();
                self.line(format!("{} = call fast double @{}(double {})", t, intr, x));
                Ok(EV { ty: CType::F64, regs: vec![t] })
            }
            "acos" => {
                let x = self.to_f64(&args[0])?;
                let t = self.t();
                self.line(format!("{} = call fast double @acos(double {})", t, x));
                Ok(EV { ty: CType::F64, regs: vec![t] })
            }
            "min" | "max" | "pow" | "atan2" => {
                let a = self.to_f64(&args[0])?;
                let b = self.to_f64(&args[1])?;
                let t = self.t();
                let callee = match name {
                    "min" => "llvm.minnum.f64",
                    "max" => "llvm.maxnum.f64",
                    "pow" => "llvm.pow.f64",
                    _ => "atan2",
                };
                self.line(format!(
                    "{} = call fast double @{}(double {}, double {})",
                    t, callee, a, b
                ));
                Ok(EV { ty: CType::F64, regs: vec![t] })
            }
            "float" => {
                let x = self.to_f64(&args[0])?;
                Ok(EV { ty: CType::F64, regs: vec![x] })
            }
            "int" => {
                if args[0].ty == CType::F64 {
                    let t = self.t();
                    self.line(format!("{} = fptosi double {} to i64", t, args[0].regs[0]));
                    Ok(EV { ty: CType::I64, regs: vec![t] })
                } else {
                    Ok(args[0].clone())
                }
            }
            "len" => {
                let elem = match &args[0].ty {
                    CType::Arr(e) => e.as_ref().clone(),
                    _ => return Err("`len` expects array".into()),
                };
                let stride = lty(self.p, &elem)?.len() as i64;
                let n = self.t();
                self.line(format!("{} = load i64, ptr {}", n, args[0].regs[0]));
                if stride == 1 {
                    Ok(EV { ty: CType::I64, regs: vec![n] })
                } else {
                    let d = self.t();
                    self.line(format!("{} = sdiv i64 {}, {}", d, n, stride));
                    Ok(EV { ty: CType::I64, regs: vec![d] })
                }
            }
            "arr" => {
                let n = &args[0].regs[0];
                let t = self.t();
                match &args[1].ty {
                    CType::F64 => {
                        self.line(format!(
                            "{} = call ptr @lu_arr_new_f64(i64 {}, double {})",
                            t, n, args[1].regs[0]
                        ));
                        Ok(EV { ty: CType::Arr(Box::new(CType::F64)), regs: vec![t] })
                    }
                    CType::I64 => {
                        self.line(format!(
                            "{} = call ptr @lu_arr_new_i64(i64 {}, i64 {})",
                            t, n, args[1].regs[0]
                        ));
                        Ok(EV { ty: CType::Arr(Box::new(CType::I64)), regs: vec![t] })
                    }
                    t => Err(format!("arr of {:?} unsupported in AOT", t)),
                }
            }
            _ => self.emit_user_call(name, args),
        }
    }
}
