use crate::abi::{self, Function, Manifest};
use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

#[path = "sdk_extra.rs"]
mod extra;

pub fn run(args: &[String]) -> Result<String, String> {
    let Some(language) = args.first().map(String::as_str) else {
        return Err(
            "usage: lu sdk <rust|cpp|julia|node|go|swift|r> [-o path] <manifest.json>".into(),
        );
    };
    let mut output = None;
    let mut input = None;
    let mut index = 1;
    while index < args.len() {
        match args[index].as_str() {
            "-o" => {
                output = Some(args.get(index + 1).ok_or("`-o` needs a file")?.clone());
                index += 2;
            }
            option if option.starts_with('-') => {
                return Err(format!("unknown sdk option `{option}`"))
            }
            path if input.is_none() => {
                input = Some(path.to_string());
                index += 1;
            }
            _ => return Err("sdk generation accepts one manifest".into()),
        }
    }
    let input = input.ok_or("sdk generation needs an ABI manifest")?;
    let input_path = Path::new(&input);
    let manifest = abi::load(input_path)?;
    if matches!(language, "node" | "go" | "swift" | "r") {
        let output = output
            .map(PathBuf::from)
            .unwrap_or_else(|| input_path.with_extension(language));
        if output.as_os_str() == "-" {
            return Err(format!(
                "{language} SDK generation needs an output directory"
            ));
        }
        std::fs::create_dir_all(&output)
            .map_err(|error| format!("cannot create {}: {error}", output.display()))?;
        for (name, contents) in extra::package(language, &manifest)? {
            let path = output.join(name);
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent)
                    .map_err(|error| format!("cannot create {}: {error}", parent.display()))?;
            }
            std::fs::write(&path, contents)
                .map_err(|error| format!("cannot write {}: {error}", path.display()))?;
        }
        return Ok(format!(
            "generated {language} SDK package in {}",
            output.display()
        ));
    }
    let (extension, generated) = match language {
        "rust" => ("rs", rust(&manifest)?),
        "cpp" | "c++" => ("hpp", cpp(&manifest)?),
        "julia" => ("jl", julia(&manifest)?),
        _ => return Err(format!("unsupported SDK language `{language}`")),
    };
    let output = output
        .map(PathBuf::from)
        .unwrap_or_else(|| input_path.with_extension(extension));
    if output.as_os_str() == "-" {
        print!("{generated}");
        Ok(format!("generated {language} SDK on stdout"))
    } else {
        std::fs::write(&output, generated)
            .map_err(|error| format!("cannot write {}: {error}", output.display()))?;
        Ok(format!("generated {language} SDK in {}", output.display()))
    }
}

fn rust(manifest: &Manifest) -> Result<String, String> {
    let enums = manifest.enums.keys().cloned().collect::<BTreeSet<_>>();
    let records = manifest.records.keys().cloned().collect::<BTreeSet<_>>();
    let mut out = String::from("// Generated by `lu sdk rust`; ABI manifest version 1.\n\n");
    if has_error_results(manifest) {
        out.push_str(
            "#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n\
             pub struct LuError { pub code: i64 }\n\n",
        );
    }
    for element in owned_elements(manifest) {
        let suffix = host_type_suffix(element)?;
        let scalar = rust_scalar(element, &enums, &records)?;
        let _ = writeln!(
            out,
            "#[repr(C)]\nstruct __LuOwned{suffix} {{ _private: [u8; 0] }}\n\
             pub struct Owned{suffix} {{ raw: *mut __LuOwned{suffix} }}\n\
             impl Owned{suffix} {{\n\
             \x20   pub fn len(&self) -> usize {{ unsafe {{ __lu_owned_{}_len(self.raw) as usize }} }}\n\
             \x20   pub fn is_empty(&self) -> bool {{ self.len() == 0 }}\n\
             \x20   pub fn as_slice(&self) -> &[{scalar}] {{ unsafe {{ core::slice::from_raw_parts(__lu_owned_{}_data(self.raw), self.len()) }} }}\n\
             \x20   pub fn as_mut_slice(&mut self) -> &mut [{scalar}] {{ let len = self.len(); unsafe {{ core::slice::from_raw_parts_mut(__lu_owned_{}_data(self.raw), len) }} }}\n\
             }}\n\
             impl Drop for Owned{suffix} {{ fn drop(&mut self) {{ unsafe {{ __lu_owned_{}_release(self.raw) }} }} }}\n",
            element, element, element, element
        );
    }
    for (name, variants) in &manifest.enums {
        let _ = writeln!(out, "pub type {name} = i64;");
        for (tag, variant) in variants.iter().enumerate() {
            let _ = writeln!(out, "pub const {name}_{variant}: {name} = {tag};");
        }
        out.push('\n');
    }
    for (name, fields) in &manifest.records {
        let _ = writeln!(
            out,
            "#[repr(C)]\n#[derive(Clone, Copy, Debug)]\npub struct {name} {{"
        );
        for field in fields {
            let _ = writeln!(
                out,
                "    pub {}: {},",
                rust_ident(&field.name),
                rust_abi_scalar(&field.ty, &enums, &records)?
            );
        }
        out.push_str("}\n\n");
    }
    let _ = writeln!(out, "#[link(name = {:?})]", manifest.library);
    out.push_str("unsafe extern \"C\" {\n");
    for element in owned_elements(manifest) {
        let suffix = host_type_suffix(element)?;
        let scalar = rust_scalar(element, &enums, &records)?;
        let _ = writeln!(
            out,
            "    #[link_name = \"lu_owned_{element}_data\"]\n\
             \x20   fn __lu_owned_{element}_data(handle: *mut __LuOwned{suffix}) -> *mut {scalar};\n\
             \x20   #[link_name = \"lu_owned_{element}_len\"]\n\
             \x20   fn __lu_owned_{element}_len(handle: *const __LuOwned{suffix}) -> i64;\n\
             \x20   #[link_name = \"lu_owned_{element}_release\"]\n\
             \x20   fn __lu_owned_{element}_release(handle: *mut __LuOwned{suffix});"
        );
    }
    for (name, function) in &manifest.exports {
        let raw_params = rust_raw_params(function, &enums, &records)?;
        let raw_ret = rust_raw_type(&function.ret, &enums, &records)?;
        let _ = writeln!(
            out,
            "    #[link_name = {:?}]\n    fn __lu_{}({}) -> {};",
            name,
            name,
            raw_params.join(", "),
            raw_ret
        );
    }
    out.push_str("}\n\n");
    for (name, function) in &manifest.exports {
        let unsafe_wrapper = function
            .params
            .iter()
            .any(|field| field.ty.starts_with("c_ptr["))
            || function.ret.starts_with("c_ptr[");
        let params = function
            .params
            .iter()
            .map(|field| {
                Ok(format!(
                    "{}: {}",
                    rust_ident(&field.name),
                    rust_api_type(&field.ty, false, &enums, &records)?
                ))
            })
            .collect::<Result<Vec<_>, String>>()?;
        let ret = if error_result(manifest, &function.ret).is_some() {
            "Result<i64, LuError>".into()
        } else {
            rust_api_type(&function.ret, true, &enums, &records)?
        };
        let _ = writeln!(
            out,
            "pub {}fn {}({}) -> {} {{",
            if unsafe_wrapper { "unsafe " } else { "" },
            name,
            params.join(", "),
            ret
        );
        let (args, prelude) = rust_call_args(function);
        for line in prelude {
            let _ = writeln!(out, "    {line}");
        }
        let call = format!("unsafe {{ __lu_{}({}) }}", name, args.join(", "));
        if let Some((status, value)) = error_result(manifest, &function.ret) {
            let _ = writeln!(out, "    let result = {call};");
            let _ = writeln!(
                out,
                "    if result.{status} == 0 {{ Ok(result.{value}) }} else {{ Err(LuError {{ code: result.{status} }}) }}"
            );
        } else if let Some(element) = array_element(&function.ret) {
            let suffix = host_type_suffix(element)?;
            let _ = writeln!(out, "    Owned{suffix} {{ raw: {call} }}");
        } else {
            match function.ret.as_str() {
                "()" => {
                    let _ = writeln!(out, "    {call};");
                }
                "bool" => {
                    let _ = writeln!(out, "    ({call}) != 0");
                }
                "str" => {
                    let _ = writeln!(out, "    let pointer = {call};");
                    out.push_str(
                    "    if pointer.is_null() || out_len <= 0 { return Vec::new(); }\n\
                     \x20   unsafe { core::slice::from_raw_parts(pointer, out_len as usize).to_vec() }\n",
                );
                }
                _ => {
                    let _ = writeln!(out, "    {call}");
                }
            }
        }
        out.push_str("}\n\n");
    }
    Ok(out)
}

fn rust_raw_params(
    function: &Function,
    enums: &BTreeSet<String>,
    records: &BTreeSet<String>,
) -> Result<Vec<String>, String> {
    let mut params = Vec::new();
    for (index, field) in function.params.iter().enumerate() {
        let name = format!("p{index}");
        match field.ty.as_str() {
            "str" => {
                params.push(format!("{name}_data: *const u8"));
                params.push(format!("{name}_len: i64"));
            }
            ty if array_element(ty).is_some() => {
                let element = rust_scalar(array_element(ty).unwrap(), enums, records)?;
                params.push(format!("{name}_data: *mut {element}"));
                params.push(format!("{name}_len: i64"));
            }
            ty if slice_element(ty, "c_slice").is_some() => {
                let element = rust_scalar(slice_element(ty, "c_slice").unwrap(), enums, records)?;
                params.push(format!("{name}_data: *const {element}"));
                params.push(format!("{name}_len: i64"));
            }
            ty if slice_element(ty, "c_mut_slice").is_some() => {
                let element =
                    rust_scalar(slice_element(ty, "c_mut_slice").unwrap(), enums, records)?;
                params.push(format!("{name}_data: *mut {element}"));
                params.push(format!("{name}_len: i64"));
            }
            ty => params.push(format!("{name}: {}", rust_raw_type(ty, enums, records)?)),
        }
    }
    if function.ret == "str" {
        params.push("out_len: *mut i64".into());
    }
    Ok(params)
}

fn rust_call_args(function: &Function) -> (Vec<String>, Vec<String>) {
    let mut args = Vec::new();
    let mut prelude = Vec::new();
    for field in &function.params {
        let name = rust_ident(&field.name);
        match field.ty.as_str() {
            "str" => {
                args.push(format!("{name}.as_ptr()"));
                args.push(format!("{name}.len() as i64"));
            }
            ty if array_element(ty).is_some() || slice_element(ty, "c_mut_slice").is_some() => {
                args.push(format!("{name}.as_mut_ptr()"));
                args.push(format!("{name}.len() as i64"));
            }
            ty if slice_element(ty, "c_slice").is_some() => {
                args.push(format!("{name}.as_ptr()"));
                args.push(format!("{name}.len() as i64"));
            }
            "bool" => args.push(format!("i64::from({name})")),
            _ => args.push(name),
        }
    }
    if function.ret == "str" {
        prelude.push("let mut out_len = 0i64;".into());
        args.push("&mut out_len".into());
    }
    (args, prelude)
}

fn rust_api_type(
    ty: &str,
    return_position: bool,
    enums: &BTreeSet<String>,
    records: &BTreeSet<String>,
) -> Result<String, String> {
    Ok(match ty {
        "str" if return_position => "Vec<u8>".into(),
        "str" => "&[u8]".into(),
        "()" => "()".into(),
        ty if return_position && array_element(ty).is_some() => {
            format!("Owned{}", host_type_suffix(array_element(ty).unwrap())?)
        }
        ty if array_element(ty).is_some() => {
            format!(
                "&mut [{}]",
                rust_scalar(array_element(ty).unwrap(), enums, records)?
            )
        }
        ty if slice_element(ty, "c_slice").is_some() => format!(
            "&[{}]",
            rust_scalar(slice_element(ty, "c_slice").unwrap(), enums, records)?
        ),
        ty if slice_element(ty, "c_mut_slice").is_some() => format!(
            "&mut [{}]",
            rust_scalar(slice_element(ty, "c_mut_slice").unwrap(), enums, records)?
        ),
        _ => rust_scalar(ty, enums, records)?,
    })
}

fn rust_raw_type(
    ty: &str,
    enums: &BTreeSet<String>,
    records: &BTreeSet<String>,
) -> Result<String, String> {
    Ok(match ty {
        "str" => "*const u8".into(),
        "bool" => "i64".into(),
        ty if array_element(ty).is_some() => format!(
            "*mut __LuOwned{}",
            host_type_suffix(array_element(ty).unwrap())?
        ),
        _ => rust_scalar(ty, enums, records)?,
    })
}

fn rust_scalar(
    ty: &str,
    enums: &BTreeSet<String>,
    records: &BTreeSet<String>,
) -> Result<String, String> {
    Ok(match ty {
        "i64" => "i64".into(),
        "f32" => "f32".into(),
        "f64" => "f64".into(),
        "bool" => "bool".into(),
        "()" => "()".into(),
        ty if ty.starts_with("c_ptr[") => "*mut core::ffi::c_void".into(),
        ty if callback_signature(ty).is_some() => rust_callback_type(ty, enums, records)?,
        ty if enums.contains(ty) || records.contains(ty) => ty.into(),
        _ => return Err(format!("unsupported Rust SDK type `{ty}`")),
    })
}

fn rust_callback_type(
    ty: &str,
    enums: &BTreeSet<String>,
    records: &BTreeSet<String>,
) -> Result<String, String> {
    let (params, ret) =
        callback_signature(ty).ok_or_else(|| format!("invalid callback type `{ty}`"))?;
    let mut raw_params = Vec::new();
    for param in params {
        match param {
            "str" => raw_params.extend(["*const u8".into(), "i64".into()]),
            ty if array_element(ty).is_some() || slice_element(ty, "c_mut_slice").is_some() => {
                let element = array_element(ty)
                    .or_else(|| slice_element(ty, "c_mut_slice"))
                    .unwrap();
                raw_params.push(format!("*mut {}", rust_scalar(element, enums, records)?));
                raw_params.push("i64".into());
            }
            ty if slice_element(ty, "c_slice").is_some() => {
                raw_params.push(format!(
                    "*const {}",
                    rust_scalar(slice_element(ty, "c_slice").unwrap(), enums, records)?
                ));
                raw_params.push("i64".into());
            }
            ty => raw_params.push(rust_raw_type(ty, enums, records)?),
        }
    }
    let raw_ret = if ret == "str" {
        raw_params.push("*mut i64".into());
        "*const u8".into()
    } else {
        rust_raw_type(ret, enums, records)?
    };
    Ok(format!(
        "Option<unsafe extern \"C\" fn({}) -> {raw_ret}>",
        raw_params.join(", ")
    ))
}

fn rust_abi_scalar(
    ty: &str,
    enums: &BTreeSet<String>,
    records: &BTreeSet<String>,
) -> Result<String, String> {
    if ty == "bool" {
        Ok("i64".into())
    } else {
        rust_scalar(ty, enums, records)
    }
}

fn cpp(manifest: &Manifest) -> Result<String, String> {
    let enums = manifest.enums.keys().cloned().collect::<BTreeSet<_>>();
    let records = manifest.records.keys().cloned().collect::<BTreeSet<_>>();
    let namespace = host_ident(&manifest.library);
    let mut out = format!(
        "// Generated by `lu sdk cpp`; ABI manifest version 1.\n\
         #pragma once\n\
         #include \"{}.h\"\n\
         #include <cstdint>\n#include <span>\n#include <string>\n#include <string_view>\n#include <utility>\n\n\
         namespace {} {{\n\n",
        manifest.library, namespace
    );
    if has_error_results(manifest) {
        out.push_str(
            "struct LuError { int64_t code; };\n\
             template <typename T> struct Result {\n\
             \x20   T value{};\n\
             \x20   LuError error{};\n\
             \x20   explicit operator bool() const { return error.code == 0; }\n\
             };\n\n",
        );
    }
    for element in owned_elements(manifest) {
        let suffix = host_type_suffix(element)?;
        let scalar = cpp_scalar(element)?;
        let _ = writeln!(
            out,
            "class Owned{suffix} {{\n\
             \x20   ::lu_owned_{element} *raw_ = nullptr;\n\
             public:\n\
             \x20   Owned{suffix}(::lu_owned_{element} *raw) : raw_(raw) {{}}\n\
             \x20   ~Owned{suffix}() {{ ::lu_owned_{element}_release(raw_); }}\n\
             \x20   Owned{suffix}(const Owned{suffix}&) = delete;\n\
             \x20   Owned{suffix}& operator=(const Owned{suffix}&) = delete;\n\
             \x20   Owned{suffix}(Owned{suffix}&& other) noexcept : raw_(std::exchange(other.raw_, nullptr)) {{}}\n\
             \x20   Owned{suffix}& operator=(Owned{suffix}&& other) noexcept {{ if (this != &other) {{ ::lu_owned_{element}_release(raw_); raw_ = std::exchange(other.raw_, nullptr); }} return *this; }}\n\
             \x20   std::span<{scalar}> span() {{ return {{::lu_owned_{element}_data(raw_), static_cast<std::size_t>(::lu_owned_{element}_len(raw_))}}; }}\n\
             \x20   std::span<const {scalar}> span() const {{ return {{::lu_owned_{element}_data(raw_), static_cast<std::size_t>(::lu_owned_{element}_len(raw_))}}; }}\n\
             }};\n"
        );
    }
    for (name, function) in &manifest.exports {
        let params = function
            .params
            .iter()
            .map(|field| {
                Ok(format!(
                    "{} {}",
                    cpp_api_type(&field.ty, false, &enums, &records)?,
                    host_ident(&field.name)
                ))
            })
            .collect::<Result<Vec<_>, String>>()?;
        let ret = if error_result(manifest, &function.ret).is_some() {
            "Result<int64_t>".into()
        } else {
            cpp_api_type(&function.ret, true, &enums, &records)?
        };
        let _ = writeln!(out, "inline {ret} {name}({}) {{", params.join(", "));
        let mut args = Vec::new();
        for field in &function.params {
            let name = host_ident(&field.name);
            match field.ty.as_str() {
                "str" => {
                    args.push(format!("{name}.data()"));
                    args.push(format!("static_cast<int64_t>({name}.size())"));
                }
                ty if array_element(ty).is_some()
                    || slice_element(ty, "c_slice").is_some()
                    || slice_element(ty, "c_mut_slice").is_some() =>
                {
                    args.push(format!("{name}.data()"));
                    args.push(format!("static_cast<int64_t>({name}.size())"));
                }
                "bool" => args.push(format!("{name} ? INT64_C(1) : INT64_C(0)")),
                _ => args.push(name),
            }
        }
        if let Some((status, value)) = error_result(manifest, &function.ret) {
            let _ = writeln!(
                out,
                "    const auto result = ::{}({});",
                name,
                args.join(", ")
            );
            let _ = writeln!(
                out,
                "    return {{result.{value}, LuError{{result.{status}}}}};"
            );
        } else if function.ret == "str" {
            out.push_str("    int64_t out_len = 0;\n");
            args.push("&out_len".into());
            let _ = writeln!(
                out,
                "    const char *pointer = ::{}({});",
                name,
                args.join(", ")
            );
            out.push_str(
                "    return pointer == nullptr || out_len <= 0\n\
                 \x20       ? std::string{}\n\
                 \x20       : std::string(pointer, static_cast<std::size_t>(out_len));\n",
            );
        } else if function.ret == "()" {
            let _ = writeln!(out, "    ::{}({});", name, args.join(", "));
        } else if function.ret == "bool" {
            let _ = writeln!(out, "    return ::{}({}) != 0;", name, args.join(", "));
        } else {
            let _ = writeln!(out, "    return ::{}({});", name, args.join(", "));
        }
        out.push_str("}\n\n");
    }
    out.push_str(&format!("}} // namespace {namespace}\n"));
    Ok(out)
}

fn cpp_api_type(
    ty: &str,
    return_position: bool,
    enums: &BTreeSet<String>,
    records: &BTreeSet<String>,
) -> Result<String, String> {
    Ok(match ty {
        "str" if return_position => "std::string".into(),
        "str" => "std::string_view".into(),
        "i64" => "int64_t".into(),
        "f32" => "float".into(),
        "f64" => "double".into(),
        "bool" => "bool".into(),
        "()" => "void".into(),
        ty if ty.starts_with("c_ptr[") => "void *".into(),
        ty if callback_signature(ty).is_some() => {
            format!("::{}", callback_typedef_name(ty))
        }
        ty if return_position && array_element(ty).is_some() => {
            format!("Owned{}", host_type_suffix(array_element(ty).unwrap())?)
        }
        ty if array_element(ty).is_some() => {
            format!("std::span<{}>", cpp_scalar(array_element(ty).unwrap())?)
        }
        ty if slice_element(ty, "c_slice").is_some() => format!(
            "std::span<const {}>",
            cpp_scalar(slice_element(ty, "c_slice").unwrap())?
        ),
        ty if slice_element(ty, "c_mut_slice").is_some() => format!(
            "std::span<{}>",
            cpp_scalar(slice_element(ty, "c_mut_slice").unwrap())?
        ),
        ty if enums.contains(ty) => "int64_t".into(),
        ty if records.contains(ty) => format!("::{ty}"),
        _ => return Err(format!("unsupported C++ SDK type `{ty}`")),
    })
}

fn cpp_scalar(ty: &str) -> Result<&'static str, String> {
    match ty {
        "i64" => Ok("int64_t"),
        "f64" => Ok("double"),
        _ => Err(format!("unsupported C++ slice element `{ty}`")),
    }
}

fn julia(manifest: &Manifest) -> Result<String, String> {
    let enums = manifest.enums.keys().cloned().collect::<BTreeSet<_>>();
    let records = manifest.records.keys().cloned().collect::<BTreeSet<_>>();
    let module = format!("Lulang{}", pascal(&manifest.library));
    let mut out = format!(
        "# Generated by `lu sdk julia`; ABI manifest version 1.\n\
         module {module}\n\nusing Libdl\n\
         const LIB = get(ENV, \"LULANG_LIBRARY\", joinpath(@__DIR__, \"lib{}.$(Libdl.dlext)\"))\n\n",
        manifest.library
    );
    if has_error_results(manifest) {
        out.push_str(
            "struct LulangError <: Exception\n\
             \x20   code::Int64\n\
             end\n\
             Base.showerror(io::IO, error::LulangError) = print(io, \"Lulang error status \", error.code)\n\n",
        );
    }
    for element in owned_elements(manifest) {
        let suffix = host_type_suffix(element)?;
        let scalar = julia_scalar(element, &enums, &records)?;
        let _ = writeln!(
            out,
            "mutable struct Owned{suffix}\n\
             \x20   handle::Ptr{{Cvoid}}\n\
             \x20   function Owned{suffix}(handle::Ptr{{Cvoid}})\n\
             \x20       value = new(handle)\n\
             \x20       finalizer(value) do owned\n\
             \x20           if owned.handle != C_NULL\n\
             \x20               ccall((:lu_owned_{element}_release, LIB), Cvoid, (Ptr{{Cvoid}},), owned.handle)\n\
             \x20               owned.handle = C_NULL\n\
             \x20           end\n\
             \x20       end\n\
             \x20       value\n\
             \x20   end\n\
             end\n\
             function Base.close(owned::Owned{suffix})\n\
             \x20   if owned.handle != C_NULL\n\
             \x20       ccall((:lu_owned_{element}_release, LIB), Cvoid, (Ptr{{Cvoid}},), owned.handle)\n\
             \x20       owned.handle = C_NULL\n\
             \x20   end\n\
             end\n\
             function borrow(owned::Owned{suffix})\n\
             \x20   length = ccall((:lu_owned_{element}_len, LIB), Int64, (Ptr{{Cvoid}},), owned.handle)\n\
             \x20   data = ccall((:lu_owned_{element}_data, LIB), Ptr{{{scalar}}}, (Ptr{{Cvoid}},), owned.handle)\n\
             \x20   unsafe_wrap(Vector{{{scalar}}}, data, length; own=false)\n\
             end\n"
        );
    }
    for (name, variants) in &manifest.enums {
        let _ = writeln!(out, "const {name} = Int64");
        for (tag, variant) in variants.iter().enumerate() {
            let _ = writeln!(out, "const {name}_{variant}::{name} = {tag}");
        }
        out.push('\n');
    }
    for (name, fields) in &manifest.records {
        let _ = writeln!(out, "struct {name}");
        for field in fields {
            let _ = writeln!(
                out,
                "    {}::{}",
                host_ident(&field.name),
                julia_abi_scalar(&field.ty, &enums, &records)?
            );
        }
        out.push_str("end\n\n");
    }
    for (name, function) in &manifest.exports {
        let params = function
            .params
            .iter()
            .map(|field| {
                Ok(format!(
                    "{}::{}",
                    host_ident(&field.name),
                    julia_api_type(&field.ty, &enums, &records)?
                ))
            })
            .collect::<Result<Vec<_>, String>>()?;
        let _ = writeln!(out, "function {name}({})", params.join(", "));
        let preserved = function
            .params
            .iter()
            .filter(|field| {
                field.ty == "str"
                    || array_element(&field.ty).is_some()
                    || slice_element(&field.ty, "c_slice").is_some()
                    || slice_element(&field.ty, "c_mut_slice").is_some()
            })
            .map(|field| host_ident(&field.name))
            .collect::<Vec<_>>();
        let indent = if preserved.is_empty() {
            "    "
        } else {
            let _ = writeln!(out, "    GC.@preserve {} begin", preserved.join(" "));
            "        "
        };
        let mut c_types = Vec::new();
        let mut args = Vec::new();
        for field in &function.params {
            let arg = host_ident(&field.name);
            match field.ty.as_str() {
                "str" => {
                    c_types.extend(["Ptr{UInt8}".into(), "Int64".into()]);
                    args.extend([format!("pointer({arg})"), format!("Int64(length({arg}))")]);
                }
                ty if array_element(ty).is_some()
                    || slice_element(ty, "c_slice").is_some()
                    || slice_element(ty, "c_mut_slice").is_some() =>
                {
                    let element = array_element(ty)
                        .or_else(|| slice_element(ty, "c_slice"))
                        .or_else(|| slice_element(ty, "c_mut_slice"))
                        .unwrap();
                    c_types.push(format!(
                        "Ptr{{{}}}",
                        julia_scalar(element, &enums, &records)?
                    ));
                    c_types.push("Int64".into());
                    args.extend([format!("pointer({arg})"), format!("Int64(length({arg}))")]);
                }
                "bool" => {
                    c_types.push("Int64".into());
                    args.push(format!("{arg} ? Int64(1) : Int64(0)"));
                }
                ty => {
                    c_types.push(julia_raw_type(ty, &enums, &records)?);
                    args.push(arg);
                }
            }
        }
        if function.ret == "str" {
            let _ = writeln!(out, "{indent}out_len = Ref{{Int64}}(0)");
            c_types.push("Ref{Int64}".into());
            args.push("out_len".into());
        }
        let tuple = if c_types.is_empty() {
            "()".into()
        } else if c_types.len() == 1 {
            format!("({},)", c_types[0])
        } else {
            format!("({})", c_types.join(", "))
        };
        let raw_ret = julia_raw_type(&function.ret, &enums, &records)?;
        let call = format!(
            "ccall((:{name}, LIB), {raw_ret}, {tuple}, {})",
            args.join(", ")
        );
        if let Some((status, value)) = error_result(manifest, &function.ret) {
            let _ = writeln!(out, "{indent}result = {call}");
            let _ = writeln!(
                out,
                "{indent}result.{status} == 0 ? result.{value} : throw(LulangError(result.{status}))"
            );
        } else if let Some(element) = array_element(&function.ret) {
            let suffix = host_type_suffix(element)?;
            let _ = writeln!(out, "{indent}Owned{suffix}({call})");
        } else {
            match function.ret.as_str() {
                "str" => {
                    let _ = writeln!(out, "{indent}raw = {call}");
                    let _ = writeln!(
                    out,
                    "{indent}raw == C_NULL || out_len[] <= 0 ? UInt8[] : copy(unsafe_wrap(Vector{{UInt8}}, raw, out_len[]; own=false))"
                );
                }
                "bool" => {
                    let _ = writeln!(out, "{indent}{call} != 0");
                }
                _ => {
                    let _ = writeln!(out, "{indent}{call}");
                }
            }
        }
        if !preserved.is_empty() {
            out.push_str("    end\n");
        }
        out.push_str("end\n\n");
    }
    out.push_str("end\n");
    Ok(out)
}

fn julia_api_type(
    ty: &str,
    enums: &BTreeSet<String>,
    records: &BTreeSet<String>,
) -> Result<String, String> {
    Ok(match ty {
        "str" => "Vector{UInt8}".into(),
        ty if array_element(ty).is_some() => format!(
            "Vector{{{}}}",
            julia_scalar(array_element(ty).unwrap(), enums, records)?
        ),
        ty if slice_element(ty, "c_slice").is_some() => format!(
            "Vector{{{}}}",
            julia_scalar(slice_element(ty, "c_slice").unwrap(), enums, records)?
        ),
        ty if slice_element(ty, "c_mut_slice").is_some() => format!(
            "Vector{{{}}}",
            julia_scalar(slice_element(ty, "c_mut_slice").unwrap(), enums, records)?
        ),
        _ => julia_scalar(ty, enums, records)?,
    })
}

fn julia_raw_type(
    ty: &str,
    enums: &BTreeSet<String>,
    records: &BTreeSet<String>,
) -> Result<String, String> {
    Ok(match ty {
        "str" => "Ptr{UInt8}".into(),
        "bool" => "Int64".into(),
        ty if array_element(ty).is_some() => "Ptr{Cvoid}".into(),
        _ => julia_scalar(ty, enums, records)?,
    })
}

fn julia_scalar(
    ty: &str,
    enums: &BTreeSet<String>,
    records: &BTreeSet<String>,
) -> Result<String, String> {
    Ok(match ty {
        "i64" => "Int64".into(),
        "f32" => "Float32".into(),
        "f64" => "Float64".into(),
        "bool" => "Bool".into(),
        "()" => "Cvoid".into(),
        ty if ty.starts_with("c_ptr[") => "Ptr{Cvoid}".into(),
        ty if callback_signature(ty).is_some() => "Ptr{Cvoid}".into(),
        ty if enums.contains(ty) || records.contains(ty) => ty.into(),
        _ => return Err(format!("unsupported Julia SDK type `{ty}`")),
    })
}

fn julia_abi_scalar(
    ty: &str,
    enums: &BTreeSet<String>,
    records: &BTreeSet<String>,
) -> Result<String, String> {
    if ty == "bool" {
        Ok("Int64".into())
    } else {
        julia_scalar(ty, enums, records)
    }
}

fn array_element(ty: &str) -> Option<&str> {
    ty.strip_prefix('[')?.strip_suffix(']')
}

fn callback_signature(ty: &str) -> Option<(Vec<&str>, &str)> {
    let inner = ty.strip_prefix("c_fn[(")?.strip_suffix(']')?;
    let close = inner.find(")->")?;
    let params = &inner[..close];
    let params = if params.is_empty() {
        Vec::new()
    } else {
        split_sdk_types(params)
    };
    Some((params, &inner[close + 3..]))
}

fn split_sdk_types(source: &str) -> Vec<&str> {
    let mut depth = 0i32;
    let mut start = 0usize;
    let mut values = Vec::new();
    for (index, byte) in source.bytes().enumerate() {
        match byte {
            b'[' | b'(' => depth += 1,
            b']' | b')' => depth -= 1,
            b',' if depth == 0 => {
                values.push(&source[start..index]);
                start = index + 1;
            }
            _ => {}
        }
    }
    values.push(&source[start..]);
    values
}

fn callback_typedef_name(type_name: &str) -> String {
    let mut hash = 0xcbf29ce484222325u64;
    for byte in type_name.bytes() {
        hash ^= u64::from(byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    format!("lu_callback_{hash:016x}")
}

fn owned_elements(manifest: &Manifest) -> BTreeSet<&str> {
    manifest
        .exports
        .values()
        .filter_map(|function| array_element(&function.ret))
        .collect()
}

fn error_result<'a>(manifest: &'a Manifest, ty: &str) -> Option<(&'a str, &'a str)> {
    let fields = manifest.records.get(ty)?;
    (fields.len() == 2
        && fields[0].name == "status"
        && fields[0].ty == "i64"
        && fields[1].name == "value"
        && fields[1].ty == "i64")
        .then(|| (fields[0].name.as_str(), fields[1].name.as_str()))
}

fn has_error_results(manifest: &Manifest) -> bool {
    manifest
        .exports
        .values()
        .any(|function| error_result(manifest, &function.ret).is_some())
}

fn host_type_suffix(element: &str) -> Result<&'static str, String> {
    match element {
        "i64" => Ok("I64"),
        "f64" => Ok("F64"),
        _ => Err(format!("unsupported owned result element `{element}`")),
    }
}

fn slice_element<'a>(ty: &'a str, kind: &str) -> Option<&'a str> {
    ty.strip_prefix(&format!("{kind}["))
        .and_then(|value| value.strip_suffix(']'))
}

fn rust_ident(name: &str) -> String {
    if matches!(
        name,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
    ) {
        format!("r#{name}")
    } else {
        name.into()
    }
}

fn host_ident(name: &str) -> String {
    let mut out = name
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect::<String>();
    if out.is_empty() || out.as_bytes()[0].is_ascii_digit() {
        out.insert(0, '_');
    }
    out
}

fn pascal(name: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(if upper { ch.to_ascii_uppercase() } else { ch });
            upper = false;
        } else {
            upper = true;
        }
    }
    if out.is_empty() {
        "Module".into()
    } else {
        out
    }
}
