use crate::abi::Manifest;
use std::collections::BTreeSet;
use std::fmt::Write as _;

pub(super) fn package(
    language: &str,
    manifest: &Manifest,
) -> Result<Vec<(String, String)>, String> {
    match language {
        "go" => go_package(manifest),
        "node" => node_package(manifest),
        "swift" => swift_package(manifest),
        "r" => r_package(manifest),
        _ => Err(format!("unsupported SDK package language `{language}`")),
    }
}

fn go_package(manifest: &Manifest) -> Result<Vec<(String, String)>, String> {
    let package = ident(&manifest.library).to_ascii_lowercase();
    let mut callbacks = BTreeSet::new();
    for function in manifest.exports.values() {
        for parameter in &function.params {
            collect_callback(&parameter.ty, &mut callbacks);
        }
        collect_callback(&function.ret, &mut callbacks);
    }
    let mut preamble = format!(
        "#cgo CFLAGS: -I${{SRCDIR}}/..\n\
         #cgo LDFLAGS: -L${{SRCDIR}}/.. -l{}\n\
         #include <stdint.h>\n#include <stdlib.h>\n#include \"../{}.h\"\n",
        manifest.library, manifest.library
    );
    for callback in &callbacks {
        let (params, ret) = callback_signature(callback)
            .ok_or_else(|| format!("invalid callback type `{callback}`"))?;
        if params
            .iter()
            .all(|ty| *ty != "bool" && go_callback_scalar(ty).is_some())
            && go_callback_scalar(ret).is_some()
        {
            let typedef = callback_typedef_name(callback);
            let c_params = params
                .iter()
                .enumerate()
                .map(|(index, ty)| format!("{} p{index}", c_scalar(ty).unwrap()))
                .collect::<Vec<_>>();
            let names = (0..params.len())
                .map(|index| format!("p{index}"))
                .collect::<Vec<_>>();
            let _ = writeln!(
                preamble,
                "static {} lu_go_call_{}(void *callback{}) {{ return (({})callback)({}); }}",
                c_scalar(ret).unwrap(),
                callback_hash(callback),
                if c_params.is_empty() {
                    String::new()
                } else {
                    format!(", {}", c_params.join(", "))
                },
                typedef,
                names.join(", ")
            );
        }
    }
    for (name, function) in &manifest.exports {
        if function.params.len() == 1
            && callback_signature(&function.params[0].ty).is_some()
            && function.ret == function.params[0].ty
        {
            let typedef = callback_typedef_name(&function.ret);
            let _ = writeln!(
                preamble,
                "static void *lu_go_{name}(void *callback) {{ return (void *){name}(({typedef})callback); }}"
            );
        }
    }

    let mut out = format!(
        "// Code generated by `lu sdk go`; DO NOT EDIT.\npackage {package}\n\n/*\n{preamble}*/\nimport \"C\"\n\n\
         import (\n    \"errors\"\n    \"runtime\"\n    \"unsafe\"\n)\n\n\
         type LuError struct {{ Code int64 }}\n\
         func (e LuError) Error() string {{ return \"Lulang error status\" }}\n\
         var ErrClosed = errors.New(\"Lulang owned result is closed\")\n\n"
    );
    for (name, fields) in &manifest.records {
        let _ = writeln!(out, "type {name} struct {{");
        for field in fields {
            let _ = writeln!(
                out,
                "    {} {}",
                pascal(&field.name),
                go_type(&field.ty, manifest, false)?
            );
        }
        out.push_str("}\n\n");
    }
    for (name, variants) in &manifest.enums {
        let _ = writeln!(out, "type {name} int64\nconst (");
        for (tag, variant) in variants.iter().enumerate() {
            let _ = writeln!(out, "    {name}_{variant} {name} = {tag}");
        }
        out.push_str(")\n\n");
    }
    for element in owned_elements(manifest) {
        let suffix = suffix(element)?;
        let scalar = go_scalar(element)?;
        let _ = writeln!(
            out,
            "type Owned{suffix} struct {{ handle *C.lu_owned_{element} }}\n\
             func newOwned{suffix}(handle *C.lu_owned_{element}) *Owned{suffix} {{ value := &Owned{suffix}{{handle}}; runtime.SetFinalizer(value, func(v *Owned{suffix}) {{ _ = v.Close() }}); return value }}\n\
             func (value *Owned{suffix}) Close() error {{ if value.handle == nil {{ return ErrClosed }}; C.lu_owned_{element}_release(value.handle); value.handle = nil; runtime.SetFinalizer(value, nil); return nil }}\n\
             func (value *Owned{suffix}) Values() []{scalar} {{ if value.handle == nil {{ return nil }}; length := int(C.lu_owned_{element}_len(value.handle)); return unsafe.Slice((*{scalar})(unsafe.Pointer(C.lu_owned_{element}_data(value.handle))), length) }}\n"
        );
    }
    for callback in &callbacks {
        let (params, ret) = callback_signature(callback).unwrap();
        if params
            .iter()
            .all(|ty| *ty != "bool" && go_callback_scalar(ty).is_some())
            && go_callback_scalar(ret).is_some()
        {
            let args = params
                .iter()
                .enumerate()
                .map(|(index, ty)| format!("p{index} {}", go_callback_scalar(ty).unwrap()))
                .collect::<Vec<_>>();
            let c_args = params
                .iter()
                .enumerate()
                .map(|(index, ty)| format!("{}(p{index})", c_go_cast(ty).unwrap()))
                .collect::<Vec<_>>();
            let signature = if args.is_empty() {
                "callback unsafe.Pointer".to_string()
            } else {
                format!("callback unsafe.Pointer, {}", args.join(", "))
            };
            let call = format!(
                "C.lu_go_call_{}(callback{})",
                callback_hash(callback),
                if c_args.is_empty() {
                    String::new()
                } else {
                    format!(", {}", c_args.join(", "))
                }
            );
            let (go_ret, body) = match ret {
                "()" => (String::new(), call),
                "bool" => (" bool".into(), format!("return {call} != 0")),
                _ => (
                    format!(" {}", go_callback_scalar(ret).unwrap()),
                    format!("return {}({call})", go_callback_scalar(ret).unwrap()),
                ),
            };
            let _ = writeln!(
                out,
                "func CallCallback{}({signature}){go_ret} {{ {body} }}\n",
                callback_hash(callback),
            );
        }
    }
    for (name, function) in &manifest.exports {
        render_go_function(&mut out, name, function, manifest)?;
    }
    let module = format!("module lulang.generated/{package}\n\ngo 1.21\n");
    Ok(vec![
        ("go.mod".into(), module),
        (format!("{package}.go"), out),
        (
            "README.md".into(),
            format!(
                "# Generated Go SDK\n\nPlace this directory beside `{}.h` and the compiled library, then run `go test` or import the module.\n",
                manifest.library
            ),
        ),
    ])
}

fn render_go_function(
    out: &mut String,
    name: &str,
    function: &crate::abi::Function,
    manifest: &Manifest,
) -> Result<(), String> {
    let go_name = pascal(name);
    let params = function
        .params
        .iter()
        .map(|field| {
            Ok(format!(
                "{} {}",
                ident(&field.name),
                go_type(&field.ty, manifest, false)?
            ))
        })
        .collect::<Result<Vec<_>, String>>()?;
    let error_record = error_result(manifest, &function.ret);
    let return_type = if error_record.is_some() {
        "(int64, error)".into()
    } else {
        go_type(&function.ret, manifest, true)?
    };
    let _ = writeln!(
        out,
        "func {go_name}({}){} {{",
        params.join(", "),
        if return_type == "" {
            String::new()
        } else {
            format!(" {return_type}")
        }
    );
    let mut args = Vec::new();
    for (index, field) in function.params.iter().enumerate() {
        let value = ident(&field.name);
        match field.ty.as_str() {
            "str" => {
                let _ = writeln!(
                    out,
                    "    p{index} := C.CBytes({value}); defer C.free(p{index})"
                );
                args.extend([
                    format!("(*C.char)(p{index})"),
                    format!("C.int64_t(len({value}))"),
                ]);
            }
            ty if array_element(ty).is_some()
                || slice_element(ty, "c_slice").is_some()
                || slice_element(ty, "c_mut_slice").is_some() =>
            {
                let element = array_element(ty)
                    .or_else(|| slice_element(ty, "c_slice"))
                    .or_else(|| slice_element(ty, "c_mut_slice"))
                    .unwrap();
                let _ = writeln!(
                    out,
                    "    var p{index} *C.{}; if len({value}) != 0 {{ p{index} = (*C.{})(unsafe.Pointer(&{value}[0])) }}",
                    c_go_name(element)?,
                    c_go_name(element)?
                );
                args.extend([format!("p{index}"), format!("C.int64_t(len({value}))")]);
            }
            "bool" => {
                let _ = writeln!(
                    out,
                    "    var p{index} C.int64_t; if {value} {{ p{index} = 1 }}"
                );
                args.push(format!("p{index}"));
            }
            ty if callback_signature(ty).is_some() => args.push(value),
            ty if manifest.records.contains_key(ty) => {
                let c_value = format!("p{index}");
                let _ = writeln!(
                    out,
                    "    {c_value} := C.{ty}{{{}}}",
                    manifest.records[ty]
                        .iter()
                        .map(|field| format!(
                            "{}: {}",
                            field.name,
                            go_to_c(
                                &format!("{value}.{}", pascal(&field.name)),
                                &field.ty,
                                manifest
                            )
                            .unwrap()
                        ))
                        .collect::<Vec<_>>()
                        .join(", ")
                );
                args.push(c_value);
            }
            ty => args.push(go_to_c(&value, ty, manifest)?),
        }
    }
    if function.ret == "str" {
        out.push_str("    var outLen C.int64_t\n");
        args.push("&outLen".into());
    }
    let callback_identity = function.params.len() == 1
        && callback_signature(&function.params[0].ty).is_some()
        && function.ret == function.params[0].ty;
    let call = if callback_identity {
        format!("C.lu_go_{name}({})", args.join(", "))
    } else {
        format!("C.{name}({})", args.join(", "))
    };
    if let Some((status, value)) = error_record {
        let _ = writeln!(out, "    result := {call}");
        let _ = writeln!(
            out,
            "    if result.{status} != 0 {{ return 0, LuError{{Code: int64(result.{status})}} }}\n    return int64(result.{value}), nil"
        );
    } else if let Some(element) = array_element(&function.ret) {
        let _ = writeln!(out, "    return newOwned{}({call})", suffix(element)?);
    } else if callback_signature(&function.ret).is_some() {
        let _ = writeln!(out, "    return unsafe.Pointer({call})");
    } else if manifest.records.contains_key(&function.ret) {
        let _ = writeln!(out, "    result := {call}");
        let _ = writeln!(
            out,
            "    return {}{{{}}}",
            function.ret,
            manifest.records[&function.ret]
                .iter()
                .map(|field| format!(
                    "{}: {}",
                    pascal(&field.name),
                    c_to_go(&format!("result.{}", field.name), &field.ty, manifest).unwrap()
                ))
                .collect::<Vec<_>>()
                .join(", ")
        );
    } else {
        match function.ret.as_str() {
            "()" => {
                let _ = writeln!(out, "    {call}");
            }
            "bool" => {
                let _ = writeln!(out, "    return {call} != 0");
            }
            "str" => {
                let _ = writeln!(
                    out,
                    "    result := {call}; if result == nil || outLen <= 0 {{ return nil }}; return C.GoBytes(unsafe.Pointer(result), C.int(outLen))"
                );
            }
            ty => {
                let _ = writeln!(out, "    return {}", c_to_go(&call, ty, manifest)?);
            }
        }
    }
    out.push_str("}\n\n");
    Ok(())
}

fn node_package(manifest: &Manifest) -> Result<Vec<(String, String)>, String> {
    let package_json = format!(
        "{{\n  \"name\": \"@lulang/{}\",\n  \"version\": \"0.1.0\",\n  \"main\": \"index.js\",\n  \"dependencies\": {{\"ffi-napi\": \"^4.0.3\", \"ref-napi\": \"^3.0.3\", \"ref-struct-di\": \"^1.1.1\"}}\n}}\n",
        ident(&manifest.library).to_ascii_lowercase()
    );
    let mut js = format!(
        "// Generated by `lu sdk node`.\n\
         const path = require('node:path');\nconst ffi = require('ffi-napi');\nconst ref = require('ref-napi');\nconst Struct = require('ref-struct-di')(ref);\n\
         const libraryPath = process.env.LULANG_LIBRARY || path.join(__dirname, '..', 'lib{}');\n",
        manifest.library
    );
    for (name, fields) in &manifest.records {
        let _ = writeln!(
            js,
            "const {name} = Struct({{{}}});",
            fields
                .iter()
                .map(|field| format!("{}: '{}'", field.name, node_ffi_type(&field.ty, manifest)))
                .collect::<Vec<_>>()
                .join(", ")
        );
    }
    let mut callbacks = BTreeSet::new();
    for function in manifest.exports.values() {
        for field in &function.params {
            collect_callback(&field.ty, &mut callbacks);
        }
        collect_callback(&function.ret, &mut callbacks);
    }
    for callback in &callbacks {
        let (params, ret) = callback_signature(callback).unwrap();
        let _ = writeln!(
            js,
            "const callback_{} = ffi.Function({}, [{}]);",
            callback_hash(callback),
            node_ffi_expr(ret, manifest),
            params
                .iter()
                .map(|ty| node_ffi_expr(ty, manifest))
                .collect::<Vec<_>>()
                .join(", ")
        );
    }
    js.push_str("const api = ffi.Library(libraryPath, {\n");
    for (name, function) in &manifest.exports {
        let mut params = Vec::new();
        for field in &function.params {
            match field.ty.as_str() {
                "str" => params.extend(["'pointer'".into(), "'int64'".into()]),
                ty if array_element(ty).is_some()
                    || slice_element(ty, "c_slice").is_some()
                    || slice_element(ty, "c_mut_slice").is_some() =>
                {
                    params.extend(["'pointer'".into(), "'int64'".into()])
                }
                ty => params.push(node_ffi_expr(ty, manifest)),
            }
        }
        if function.ret == "str" {
            params.push("'pointer'".into());
        }
        let _ = writeln!(
            js,
            "  {name}: [{}, [{}]],",
            node_raw_return_expr(&function.ret, manifest),
            params.join(", ")
        );
    }
    for element in owned_elements(manifest) {
        let _ = writeln!(
            js,
            "  lu_owned_{element}_data: ['pointer', ['pointer']],\n  lu_owned_{element}_len: ['int64', ['pointer']],\n  lu_owned_{element}_release: ['void', ['pointer']],"
        );
    }
    js.push_str("});\n");
    for element in owned_elements(manifest) {
        let suffix = suffix(element)?;
        let (array, bytes) = if element == "f64" {
            ("Float64Array", 8)
        } else {
            ("BigInt64Array", 8)
        };
        let _ = writeln!(
            js,
            "class Owned{suffix} {{\n\
             \x20 constructor(handle) {{ this.handle = handle; }}\n\
             \x20 get length() {{ return this.handle ? Number(api.lu_owned_{element}_len(this.handle)) : 0; }}\n\
             \x20 values() {{ const length = this.length; if (!length) return new {array}(); const view = ref.reinterpret(api.lu_owned_{element}_data(this.handle), length * {bytes}, 0); return new {array}(view.buffer, view.byteOffset, length); }}\n\
             \x20 close() {{ if (this.handle) {{ api.lu_owned_{element}_release(this.handle); this.handle = null; }} }}\n\
             }}"
        );
    }
    for (name, function) in &manifest.exports {
        let params = function
            .params
            .iter()
            .map(|field| ident(&field.name))
            .collect::<Vec<_>>();
        let _ = writeln!(js, "function {name}({}) {{", params.join(", "));
        let mut args = Vec::new();
        for field in &function.params {
            let value = ident(&field.name);
            match field.ty.as_str() {
                "str" => {
                    let buffer = format!("{value}Buffer");
                    let _ = writeln!(js, "  const {buffer} = Buffer.from({value});");
                    args.extend([buffer.clone(), format!("{buffer}.length")]);
                }
                ty if array_element(ty).is_some()
                    || slice_element(ty, "c_slice").is_some()
                    || slice_element(ty, "c_mut_slice").is_some() =>
                {
                    let buffer = format!("{value}Buffer");
                    let _ = writeln!(
                        js,
                        "  const {buffer} = Buffer.from({value}.buffer, {value}.byteOffset, {value}.byteLength);"
                    );
                    args.extend([buffer, format!("{value}.length")]);
                }
                "bool" => args.push(format!("{value} ? 1 : 0")),
                ty if manifest.records.contains_key(ty) => args.push(format!(
                    "{value} instanceof {ty} ? {value} : new {ty}({value})"
                )),
                _ => args.push(value),
            }
        }
        if function.ret == "str" {
            js.push_str("  const outLength = ref.alloc('int64');\n");
            args.push("outLength".into());
        }
        let call = format!("api.{name}({})", args.join(", "));
        if let Some((status, value)) = error_result(manifest, &function.ret) {
            let _ = writeln!(
                js,
                "  const result = {call}; if (Number(result.{status}) !== 0) throw Object.assign(new Error(`Lulang error status ${{result.{status}}}`), {{ code: Number(result.{status}) }}); return Number(result.{value});"
            );
        } else if let Some(element) = array_element(&function.ret) {
            let _ = writeln!(js, "  return new Owned{}({call});", suffix(element)?);
        } else {
            match function.ret.as_str() {
                "()" => {
                    let _ = writeln!(js, "  {call};");
                }
                "bool" => {
                    let _ = writeln!(js, "  return Number({call}) !== 0;");
                }
                "str" => {
                    let _ = writeln!(
                        js,
                        "  const pointer = {call}; const length = Number(outLength.deref()); return !pointer || length <= 0 ? Buffer.alloc(0) : Buffer.from(ref.reinterpret(pointer, length, 0));"
                    );
                }
                _ => {
                    let _ = writeln!(js, "  return {call};");
                }
            }
        }
        js.push_str("}\n");
    }
    js.push_str("module.exports = { api");
    for name in manifest.records.keys() {
        let _ = write!(js, ", {name}");
    }
    for element in owned_elements(manifest) {
        let _ = write!(js, ", Owned{}", suffix(element)?);
    }
    for name in manifest.exports.keys() {
        let _ = write!(js, ", {name}");
    }
    js.push_str(" };\n");
    Ok(vec![
        ("package.json".into(), package_json),
        ("index.js".into(), js),
        (
            "README.md".into(),
            "# Generated Node SDK\n\nRun `npm install`, set `LULANG_LIBRARY` to the generated shared library, then import `api` from this package. Buffers and typed arrays can be passed as pointer arguments without copying.\n".into(),
        ),
    ])
}

fn swift_package(manifest: &Manifest) -> Result<Vec<(String, String)>, String> {
    let module = format!("Lulang{}", pascal(&manifest.library));
    let package = format!(
        "// swift-tools-version: 5.9\nimport PackageDescription\nlet package = Package(name: \"{module}\", products: [.library(name: \"{module}\", targets: [\"{module}\"])], targets: [.systemLibrary(name: \"C{module}\", path: \"Sources/C{module}\"), .target(name: \"{module}\", dependencies: [\"C{module}\"], linkerSettings: [.unsafeFlags([\"-L\", \"..\"])])])\n"
    );
    let module_map = format!(
        "module C{module} {{\n  header \"shim.h\"\n  link \"{}\"\n  export *\n}}\n",
        manifest.library
    );
    let shim = format!("#include \"../../../{}.h\"\n", manifest.library);
    let mut swift = format!(
        "// Generated by `lu sdk swift`.\n@_exported import C{module}\nimport Foundation\n\npublic struct LulangError: Error {{ public let code: Int64 }}\n\n"
    );
    for element in owned_elements(manifest) {
        let suffix = suffix(element)?;
        let scalar = swift_type(element, manifest);
        let _ = writeln!(
            swift,
            "public final class Owned{suffix} {{\n\
             \x20   private var handle: OpaquePointer?\n\
             \x20   init(_ handle: OpaquePointer?) {{ self.handle = handle }}\n\
             \x20   deinit {{ close() }}\n\
             \x20   public func close() {{ if let handle {{ lu_owned_{element}_release(handle); self.handle = nil }} }}\n\
             \x20   public var values: UnsafeMutableBufferPointer<{scalar}> {{\n\
             \x20       guard let handle else {{ return .init(start: nil, count: 0) }}\n\
             \x20       return .init(start: lu_owned_{element}_data(handle), count: Int(lu_owned_{element}_len(handle)))\n\
             \x20   }}\n\
             }}\n"
        );
    }
    for (name, function) in &manifest.exports {
        let params = function
            .params
            .iter()
            .map(|field| {
                let modifier = if slice_element(&field.ty, "c_mut_slice").is_some()
                    || array_element(&field.ty).is_some()
                {
                    "inout "
                } else {
                    ""
                };
                format!(
                    "_ {}: {modifier}{}",
                    ident(&field.name),
                    swift_type(&field.ty, manifest)
                )
            })
            .collect::<Vec<_>>();
        let ret = if error_result(manifest, &function.ret).is_some() {
            " throws -> Int64".into()
        } else if function.ret == "()" {
            String::new()
        } else if let Some(element) = array_element(&function.ret) {
            format!(" -> Owned{}", suffix(element)?)
        } else {
            format!(" -> {}", swift_type(&function.ret, manifest))
        };
        let _ = writeln!(
            swift,
            "public func {}({}){} {{",
            pascal(name),
            params.join(", "),
            ret
        );
        let buffers = function
            .params
            .iter()
            .enumerate()
            .filter(|(_, field)| {
                field.ty == "str"
                    || array_element(&field.ty).is_some()
                    || slice_element(&field.ty, "c_slice").is_some()
                    || slice_element(&field.ty, "c_mut_slice").is_some()
            })
            .collect::<Vec<_>>();
        if buffers.len() > 1 {
            swift.push_str(
                "    fatalError(\"use the imported C ABI for multi-buffer signatures\")\n}\n\n",
            );
            continue;
        }
        let mut args = Vec::new();
        for (index, field) in function.params.iter().enumerate() {
            let value = ident(&field.name);
            if buffers
                .first()
                .is_some_and(|(buffer_index, _)| *buffer_index == index)
            {
                args.extend(["buffer.baseAddress".into(), "Int64(buffer.count)".into()]);
            } else if field.ty == "bool" {
                args.push(format!("{value} ? 1 : 0"));
            } else {
                args.push(value);
            }
        }
        if function.ret == "str" {
            args.push("&outLength".into());
        }
        let call = format!("{name}({})", args.join(", "));
        let mut body = String::new();
        if function.ret == "str" {
            body.push_str("var outLength: Int64 = 0\n");
            let _ = writeln!(body, "let pointer = {call}");
            body.push_str("guard let pointer, outLength > 0 else { return [] }\nreturn Array(UnsafeBufferPointer(start: UnsafeRawPointer(pointer).assumingMemoryBound(to: UInt8.self), count: Int(outLength)))");
        } else if let Some((status, value)) = error_result(manifest, &function.ret) {
            let _ = writeln!(body, "let result = {call}");
            let _ = writeln!(
                body,
                "if result.{status} != 0 {{ throw LulangError(code: result.{status}) }}\nreturn result.{value}"
            );
        } else if let Some(element) = array_element(&function.ret) {
            let _ = write!(body, "return Owned{}({call})", suffix(element)?);
        } else {
            match function.ret.as_str() {
                "()" => body.push_str(&call),
                "bool" => {
                    let _ = write!(body, "return {call} != 0");
                }
                _ => {
                    let _ = write!(body, "return {call}");
                }
            }
        }
        if let Some((_, field)) = buffers.first() {
            let value = ident(&field.name);
            let method = if field.ty == "str" {
                "withUnsafeBytes"
            } else if slice_element(&field.ty, "c_mut_slice").is_some()
                || array_element(&field.ty).is_some()
            {
                "withUnsafeMutableBufferPointer"
            } else {
                "withUnsafeBufferPointer"
            };
            let _ = writeln!(swift, "    return {value}.{method} {{ rawBuffer in");
            if field.ty == "str" {
                swift.push_str("        let buffer = rawBuffer.bindMemory(to: CChar.self)\n");
            } else {
                swift.push_str("        let buffer = rawBuffer\n");
            }
            for line in body.lines() {
                let _ = writeln!(swift, "        {line}");
            }
            swift.push_str("    }\n");
        } else {
            for line in body.lines() {
                let _ = writeln!(swift, "    {line}");
            }
        }
        swift.push_str("}\n\n");
    }
    Ok(vec![
        ("Package.swift".into(), package),
        (format!("Sources/C{module}/module.modulemap"), module_map),
        (format!("Sources/C{module}/shim.h"), shim),
        (format!("Sources/{module}/{module}.swift"), swift),
        (
            "README.md".into(),
            format!("# Generated Swift SDK\n\nPlace this package beside `{}.h` and its library. SwiftPM imports the exact C ABI through `C{module}` and provides convenience wrappers where Swift can preserve the signature without hiding pointer lifetimes.\n", manifest.library),
        ),
    ])
}

fn r_package(manifest: &Manifest) -> Result<Vec<(String, String)>, String> {
    let package = format!("Lulang{}", pascal(&manifest.library));
    let description = format!(
        "Package: {package}\nType: Package\nTitle: Generated Lulang ABI Bindings\nVersion: 0.1.0\nDescription: Generated bindings for {}.\nLicense: MIT\nEncoding: UTF-8\nNeedsCompilation: yes\n",
        manifest.library
    );
    let namespace = "useDynLib(".to_string()
        + &package
        + ", .registration=TRUE)\nexportPattern(\"^[[:alpha:]]+\")\n";
    let mut r = String::from("# Generated by `lu sdk r`.\n");
    for (name, function) in &manifest.exports {
        let args = function
            .params
            .iter()
            .map(|field| ident(&field.name))
            .collect::<Vec<_>>();
        let _ = writeln!(
            r,
            "{name} <- function({}) .Call(C_{name}{})",
            args.join(", "),
            if args.is_empty() {
                String::new()
            } else {
                format!(", {}", args.join(", "))
            }
        );
    }
    let mut c = format!(
        "#include <R.h>\n#include <Rinternals.h>\n#include <R_ext/Rdynload.h>\n#include <stdint.h>\n#include <string.h>\n#include \"../../{}.h\"\n\n",
        manifest.library
    );
    for (name, function) in &manifest.exports {
        let r_params = function
            .params
            .iter()
            .enumerate()
            .map(|(index, _)| format!("SEXP p{index}"))
            .collect::<Vec<_>>();
        let _ = writeln!(c, "SEXP C_{name}({}) {{", r_params.join(", "));
        let mut args = Vec::new();
        for (index, field) in function.params.iter().enumerate() {
            match field.ty.as_str() {
                "i64" => args.push(format!("(int64_t)Rf_asReal(p{index})")),
                "f32" => args.push(format!("(float)Rf_asReal(p{index})")),
                "f64" => args.push(format!("Rf_asReal(p{index})")),
                "bool" => args.push(format!("Rf_asLogical(p{index}) ? INT64_C(1) : INT64_C(0)")),
                "str" => args.extend([
                    format!("(const char *)RAW(p{index})"),
                    format!("(int64_t)XLENGTH(p{index})"),
                ]),
                ty if array_element(ty) == Some("f64")
                    || slice_element(ty, "c_slice") == Some("f64")
                    || slice_element(ty, "c_mut_slice") == Some("f64") =>
                {
                    args.extend([
                        format!("REAL(p{index})"),
                        format!("(int64_t)XLENGTH(p{index})"),
                    ]);
                }
                ty if callback_signature(ty).is_some() => {
                    args.push(format!(
                        "({})R_ExternalPtrAddr(p{index})",
                        callback_typedef_name(ty)
                    ));
                }
                ty if ty.starts_with("c_ptr[") => {
                    args.push(format!("R_ExternalPtrAddr(p{index})"));
                }
                ty if manifest.records.contains_key(ty) => {
                    let fields = &manifest.records[ty];
                    let _ = writeln!(c, "  {ty} value{index} = {{0}};");
                    for (field_index, record_field) in fields.iter().enumerate() {
                        let value = match record_field.ty.as_str() {
                            "i64" => format!("(int64_t)Rf_asReal(VECTOR_ELT(p{index}, {field_index}))"),
                            "f32" => format!("(float)Rf_asReal(VECTOR_ELT(p{index}, {field_index}))"),
                            "f64" => format!("Rf_asReal(VECTOR_ELT(p{index}, {field_index}))"),
                            "bool" => format!("Rf_asLogical(VECTOR_ELT(p{index}, {field_index})) ? INT64_C(1) : INT64_C(0)"),
                            other => return Err(format!("unsupported R record field `{other}`")),
                        };
                        let _ = writeln!(c, "  value{index}.{} = {value};", record_field.name);
                    }
                    args.push(format!("value{index}"));
                }
                ty => return Err(format!("unsupported R SDK parameter `{ty}`")),
            }
        }
        if function.ret == "str" {
            c.push_str("  int64_t out_len = 0;\n");
            args.push("&out_len".into());
        }
        let call = format!("{name}({})", args.join(", "));
        if let Some((status, value)) = error_result(manifest, &function.ret) {
            let _ = writeln!(c, "  {} result = {call};", function.ret);
            let _ = writeln!(
                c,
                "  if (result.{status} != 0) Rf_error(\"Lulang error status %lld\", (long long)result.{status});\n  return Rf_ScalarReal((double)result.{value});"
            );
        } else if let Some(element) = array_element(&function.ret) {
            let scalar = match element {
                "i64" => "int64_t",
                "f64" => "double",
                _ => return Err(format!("unsupported R owned element `{element}`")),
            };
            let sexp = if element == "f64" {
                "REALSXP"
            } else {
                "REALSXP"
            };
            let _ = writeln!(c, "  lu_owned_{element} *handle = {call};");
            let _ = writeln!(
                c,
                "  int64_t length = lu_owned_{element}_len(handle);\n  {scalar} *data = lu_owned_{element}_data(handle);\n  SEXP result = PROTECT(Rf_allocVector({sexp}, (R_xlen_t)length));\n  for (int64_t i = 0; i < length; i++) REAL(result)[i] = (double)data[i];\n  lu_owned_{element}_release(handle);\n  UNPROTECT(1);\n  return result;"
            );
        } else if manifest.records.contains_key(&function.ret) {
            let fields = &manifest.records[&function.ret];
            let _ = writeln!(c, "  {} value = {call};", function.ret);
            let _ = writeln!(
                c,
                "  SEXP result = PROTECT(Rf_allocVector(VECSXP, {}));\n  SEXP names = PROTECT(Rf_allocVector(STRSXP, {}));",
                fields.len(),
                fields.len()
            );
            for (index, field) in fields.iter().enumerate() {
                let value = if field.ty == "bool" {
                    format!("Rf_ScalarLogical(value.{} != 0)", field.name)
                } else {
                    format!("Rf_ScalarReal((double)value.{})", field.name)
                };
                let _ = writeln!(
                    c,
                    "  SET_VECTOR_ELT(result, {index}, {value}); SET_STRING_ELT(names, {index}, Rf_mkChar(\"{}\"));",
                    field.name
                );
            }
            c.push_str("  Rf_setAttrib(result, R_NamesSymbol, names);\n  UNPROTECT(2);\n  return result;\n");
        } else {
            match function.ret.as_str() {
                "()" => {
                    let _ = writeln!(c, "  {call};\n  return R_NilValue;");
                }
                "bool" => {
                    let _ = writeln!(c, "  return Rf_ScalarLogical({call} != 0);");
                }
                "i64" | "f32" | "f64" => {
                    let _ = writeln!(c, "  return Rf_ScalarReal((double){call});");
                }
                "str" => {
                    let _ = writeln!(
                        c,
                        "  const char *data = {call};\n  SEXP result = PROTECT(Rf_allocVector(RAWSXP, (R_xlen_t)out_len));\n  if (data != NULL && out_len > 0) memcpy(RAW(result), data, (size_t)out_len);\n  UNPROTECT(1);\n  return result;"
                    );
                }
                ty if callback_signature(ty).is_some() || ty.starts_with("c_ptr[") => {
                    let _ = writeln!(
                        c,
                        "  return R_MakeExternalPtr((void *){call}, R_NilValue, R_NilValue);"
                    );
                }
                ty => return Err(format!("unsupported R SDK return `{ty}`")),
            }
        }
        c.push_str("}\n\n");
    }
    c.push_str("static const R_CallMethodDef call_methods[] = {\n");
    for (name, function) in &manifest.exports {
        let _ = writeln!(
            c,
            "  {{\"C_{name}\", (DL_FUNC)&C_{name}, {}}},",
            function.params.len()
        );
    }
    let _ = writeln!(
        c,
        "  {{NULL, NULL, 0}}\n}};\nvoid R_init_{package}(DllInfo *dll) {{ R_registerRoutines(dll, NULL, call_methods, NULL, NULL); R_useDynamicSymbols(dll, FALSE); }}"
    );
    let makevars = format!(
        "PKG_CPPFLAGS = -I../..\nPKG_LIBS = -L../.. -l{}\n",
        manifest.library
    );
    Ok(vec![
        ("DESCRIPTION".into(), description),
        ("NAMESPACE".into(), namespace),
        (format!("R/{package}.R"), r),
        (format!("src/{package}.c"), c),
        ("src/Makevars".into(), makevars),
        (
            "README.md".into(),
            format!("# Generated R SDK\n\nRun `R CMD INSTALL .` after placing this package beside `{}.h` and its shared library. The generated R functions are registered through `.Call` adapters.\n", manifest.library),
        ),
    ])
}

fn go_type(ty: &str, manifest: &Manifest, return_position: bool) -> Result<String, String> {
    Ok(match ty {
        "()" => String::new(),
        "i64" => "int64".into(),
        "f32" => "float32".into(),
        "f64" => "float64".into(),
        "bool" => "bool".into(),
        "str" => "[]byte".into(),
        ty if ty.starts_with("c_ptr[") || callback_signature(ty).is_some() => {
            "unsafe.Pointer".into()
        }
        ty if return_position && array_element(ty).is_some() => {
            format!("*Owned{}", suffix(array_element(ty).unwrap())?)
        }
        ty if array_element(ty).is_some() => {
            format!("[]{}", go_scalar(array_element(ty).unwrap())?)
        }
        ty if slice_element(ty, "c_slice").is_some() => {
            format!("[]{}", go_scalar(slice_element(ty, "c_slice").unwrap())?)
        }
        ty if slice_element(ty, "c_mut_slice").is_some() => {
            format!(
                "[]{}",
                go_scalar(slice_element(ty, "c_mut_slice").unwrap())?
            )
        }
        ty if manifest.enums.contains_key(ty) || manifest.records.contains_key(ty) => ty.into(),
        _ => return Err(format!("unsupported Go SDK type `{ty}`")),
    })
}

fn go_scalar(ty: &str) -> Result<&'static str, String> {
    match ty {
        "i64" => Ok("int64"),
        "f64" => Ok("float64"),
        _ => Err(format!("unsupported Go slice element `{ty}`")),
    }
}

fn c_go_name(ty: &str) -> Result<&'static str, String> {
    match ty {
        "i64" => Ok("int64_t"),
        "f64" => Ok("double"),
        _ => Err(format!("unsupported C scalar `{ty}`")),
    }
}

fn go_to_c(value: &str, ty: &str, manifest: &Manifest) -> Result<String, String> {
    Ok(match ty {
        "i64" => format!("C.int64_t({value})"),
        "f32" => format!("C.float({value})"),
        "f64" => format!("C.double({value})"),
        ty if ty.starts_with("c_ptr[") => value.into(),
        ty if manifest.enums.contains_key(ty) => format!("C.int64_t({value})"),
        _ => value.into(),
    })
}

fn c_to_go(value: &str, ty: &str, manifest: &Manifest) -> Result<String, String> {
    Ok(match ty {
        "i64" => format!("int64({value})"),
        "f32" => format!("float32({value})"),
        "f64" => format!("float64({value})"),
        ty if ty.starts_with("c_ptr[") => format!("unsafe.Pointer({value})"),
        ty if manifest.enums.contains_key(ty) => format!("{ty}({value})"),
        _ => value.into(),
    })
}

fn go_callback_scalar(ty: &str) -> Option<&'static str> {
    match ty {
        "i64" => Some("int64"),
        "f32" => Some("float32"),
        "f64" => Some("float64"),
        "bool" => Some("bool"),
        "()" => Some(""),
        _ => None,
    }
}

fn c_go_cast(ty: &str) -> Option<&'static str> {
    match ty {
        "i64" => Some("C.int64_t"),
        "f32" => Some("C.float"),
        "f64" => Some("C.double"),
        "bool" => Some("C.int64_t"),
        _ => None,
    }
}

fn c_scalar(ty: &str) -> Option<&'static str> {
    match ty {
        "i64" | "bool" => Some("int64_t"),
        "f32" => Some("float"),
        "f64" => Some("double"),
        "()" => Some("void"),
        _ => None,
    }
}

fn swift_type(ty: &str, manifest: &Manifest) -> String {
    match ty {
        "()" => "Void".into(),
        "i64" => "Int64".into(),
        "f32" => "Float".into(),
        "f64" => "Double".into(),
        "bool" => "Bool".into(),
        "str" => "[UInt8]".into(),
        ty if ty.starts_with("c_ptr[") => "UnsafeMutableRawPointer?".into(),
        ty if callback_signature(ty).is_some() => callback_typedef_name(ty),
        ty if array_element(ty).is_some()
            || slice_element(ty, "c_slice").is_some()
            || slice_element(ty, "c_mut_slice").is_some() =>
        {
            let element = array_element(ty)
                .or_else(|| slice_element(ty, "c_slice"))
                .or_else(|| slice_element(ty, "c_mut_slice"))
                .unwrap();
            format!("[{}]", swift_type(element, manifest))
        }
        ty if manifest.enums.contains_key(ty) => "Int64".into(),
        _ => ty.into(),
    }
}

fn node_ffi_type(ty: &str, manifest: &Manifest) -> String {
    match ty {
        "i64" | "bool" => "int64".into(),
        "f32" => "float".into(),
        "f64" => "double".into(),
        "()" => "void".into(),
        "str" => "pointer".into(),
        ty if ty.starts_with("c_ptr[")
            || array_element(ty).is_some()
            || callback_signature(ty).is_some() =>
        {
            "pointer".into()
        }
        ty if manifest.enums.contains_key(ty) => "int64".into(),
        ty if manifest.records.contains_key(ty) => ty.into(),
        _ => "pointer".into(),
    }
}

fn node_ffi_expr(ty: &str, manifest: &Manifest) -> String {
    if callback_signature(ty).is_some() {
        format!("callback_{}", callback_hash(ty))
    } else if manifest.records.contains_key(ty) {
        ty.into()
    } else {
        format!("'{}'", node_ffi_type(ty, manifest))
    }
}

fn node_raw_return_expr(ty: &str, manifest: &Manifest) -> String {
    if array_element(ty).is_some() {
        "'pointer'".into()
    } else {
        node_ffi_expr(ty, manifest)
    }
}

fn array_element(ty: &str) -> Option<&str> {
    ty.strip_prefix('[')?.strip_suffix(']')
}

fn slice_element<'a>(ty: &'a str, kind: &str) -> Option<&'a str> {
    ty.strip_prefix(&format!("{kind}["))
        .and_then(|value| value.strip_suffix(']'))
}

fn callback_signature(ty: &str) -> Option<(Vec<&str>, &str)> {
    let inner = ty.strip_prefix("c_fn[(")?.strip_suffix(']')?;
    let close = inner.find(")->")?;
    let params = if close == 0 {
        Vec::new()
    } else {
        inner[..close].split(',').collect()
    };
    Some((params, &inner[close + 3..]))
}

fn collect_callback(ty: &str, callbacks: &mut BTreeSet<String>) {
    if callback_signature(ty).is_some() {
        callbacks.insert(ty.into());
    }
}

fn callback_typedef_name(type_name: &str) -> String {
    format!("lu_callback_{}", callback_hash(type_name))
}

fn callback_hash(type_name: &str) -> String {
    let mut hash = 0xcbf29ce484222325u64;
    for byte in type_name.bytes() {
        hash ^= u64::from(byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    format!("{hash:016x}")
}

fn owned_elements(manifest: &Manifest) -> BTreeSet<&str> {
    manifest
        .exports
        .values()
        .filter_map(|function| array_element(&function.ret))
        .collect()
}

fn error_result<'a>(manifest: &'a Manifest, ty: &str) -> Option<(&'a str, &'a str)> {
    let fields = manifest.records.get(ty)?;
    (fields.len() == 2
        && fields[0].name == "status"
        && fields[0].ty == "i64"
        && fields[1].name == "value"
        && fields[1].ty == "i64")
        .then(|| (fields[0].name.as_str(), fields[1].name.as_str()))
}

fn suffix(element: &str) -> Result<&'static str, String> {
    match element {
        "i64" => Ok("I64"),
        "f64" => Ok("F64"),
        _ => Err(format!("unsupported owned element `{element}`")),
    }
}

fn ident(value: &str) -> String {
    let mut out = value
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect::<String>();
    if out.is_empty() || out.as_bytes()[0].is_ascii_digit() {
        out.insert(0, '_');
    }
    out
}

fn pascal(value: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(if upper { ch.to_ascii_uppercase() } else { ch });
            upper = ch == '_';
        } else {
            upper = true;
        }
    }
    out.replace('_', "")
}
